### ISSUE TITLE
[linuxmint/cinnamon-spices-applets] multicore-sys-monitor@ccadeptic23: Applet does not adapt size to panel size

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#868] opened 2017-06-06 21:59 UTC
[Have you read the guidelines for contributing?]: <> (Before opening an issue, please read the guidelines for contributing linked above. Else the issue will be closed. Also don't forget to notify the author.)

[Notify author of applet]: <> (You should mention the author on GitHub by typing @ plus his/her username to trigger a notification and bring his/her attention to an issue or pull request. You find the username of the author on the cinnamon spices website: https://cinnamon-spices.linuxmint.com/)
@jaszhix 

[Issue]: <> (Describe your issue below.)

If I change the panel size, this applet does not adapt its size to the available space. Every other applet changes its size to fill the available size of the panel.

**Comment by jaszhix** [comment] 2017-06-06 22:15
This is a duplicate of #104.

**Closed by jaszhix** 2017-06-06 22:15 UTC

**Comment by sphh** [comment] 2017-06-07 07:26
Sorry, but this is not a duplicate of #104. #104 asks for a vertical centering if the panel is higher than the size of this applet, whereas I suggest that the applet expands to fill the whole available vertical space. This is definitely different to #104.

Can I suggest that you re-open this bug?

**Comment by jaszhix** [comment] 2017-06-07 08:49
They're similar in scope, so I merged your feature request in with #104.
