### ISSUE TITLE
darkMode@linuxedo.com: Applet does not work

### ISSUE THREAD

**Issue by DonLH** [linuxmint/cinnamon-spices-applets#4224] opened 2022-01-14 08:09 UTC
```
 * Build date: Updated on 2021-12-26 18:19:59
 * Cinnamon version: Cinnamon 5.2.7
 * Distribution: Linux Mint 20.3
 * Graphics hardware *and* driver used: Intel Corporation 4 Series Chipset Integrated Graphics Controller
 * Snippet or attachment of ~/.cinnamon/glass.log: N/A
 * Snippet or attachment of ~/.xsession-errors: N/A

 ```

**Notify author of applet**
@slgobinath

**Issue**

Applet does not work and configuration can't be opened.

**Steps to reproduce**

Switching to dark mode does nothing and configuration window does not show.

**Expected behaviour**

Should be working.

**Other information**

**Comment by slgobinath** [comment] 2022-01-16 13:21
Hi,
I have the same configuration here but couldn't reproduce this error. If the applet is not configured, switching the mode from the applet menu won't make any changes. So the problem is identifying why the config dialog is not opening.

Can you attach the `~/.xsession-errors` file here?

**Comment by DonLH** [comment] 2022-01-16 15:32
`~/.xsession-errors` file: [xsession-errors.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/7877240/xsession-errors.zip)

**Comment by DonLH** [comment] 2022-01-16 15:53
Solved this problem by making `~/.local/share/icons` directory which was missing for some reason.

**Comment by slgobinath** [comment] 2022-01-16 16:28
Thanks. Missing directory shouldn't cause the applet to crash or not working. I will fix it soon.

**Comment by dvoraking** [comment] 2022-01-25 20:14
> Solved this problem by making `~/.local/share/icons` directory which was missing for some reason.

Thanks for the save. I had the same issue on Linux Mint 20.2 and 20.3 until this fix.

**Comment by sreelid** [comment] 2022-07-16 11:29
Same problem LMDE5 the config dialog is not opening. I do have ~/.local/share/icons folder. So that is not the problem.

**Comment by sreelid** [comment] 2022-07-18 17:31
> Same problem LMDE5 the config dialog is not opening. I do have ~/.local/share/icons folder. So that is not the problem.

After update it is fixed now. Working. Thanks.

**Closed** 2022-07-28 18:46 UTC
