### ISSUE TITLE
Icing Task Manager : High Idle CPU Usage since last few updates

### ISSUE THREAD

**Issue by panks103** [linuxmint/cinnamon-spices-applets#1173] opened 2017-08-21 16:04 UTC
[Notify author of applet]: @jaszhix 

 - Distribution : LinuxMint 18.2 Sonya
 - Cinnamon version : Cinnamon 3.4.6
 - Applet version : 5.3.3
 - ~/.cinnamon/glass.log (Use pastebin or a small snippet that's relavent to the issue.)

[Issue]: Since last few updates the idle CPU usage for Icing Task Manager is very high. Initially after the cinnamon desktop loads the CPU usage is low but after a few minutes the CPU usage progressively increases and rises upto 25% on idle. The issue gets resolved after the applet is removed.

**Comment by jaszhix** [comment] 2017-08-21 18:37
For ITM since it has a ton of options, I will need your settings.json and preferably glass.log and .xsession error files in case there is more information that could point to a cause.

**Comment by panks103** [comment] 2017-08-22 04:00
Thank you for your response, I will add the setting details, logs etc in some time, please bear with me.

**Comment by Piiit** [comment] 2017-08-22 13:27
@jaszhix I have the same problem. I'll send you some information.

- Distribution: Linux Mint 18.2
 - Cinnamon version: 3.4.6
 - Applet version: 2017-08-15
 - ~/.cinnamon/glass.log: https://gist.github.com/12a8aa4b948526be4c6b73ab30d08ae1
 - ~/.xsession-errors: https://gist.github.com/df3883271bde56c300323ffc77fd0a17

I have also other applets installed as you see, but when I disable ITM this error does not occur anymore.

**Comment by Protarios** [comment] 2017-08-24 06:54
Same issue here:
After a while on high CPU load cinnamon crashes into fallback mode.

Distribution: Linux Mint 18.2
Cinnamon version: 3.4.6
Applet version: 2017-08-15
~/.cinnamon/glass.log: [https://gist.github.com/Protarios/d494faf88b6fa9c7f8d079d5c3e5f2a4](https://gist.github.com/Protarios/d494faf88b6fa9c7f8d079d5c3e5f2a4)
~/.xsession-errors: [https://gist.github.com/Protarios/740e69d6f0925bf42705b06160f11a08](https://gist.github.com/Protarios/740e69d6f0925bf42705b06160f11a08)

**Comment by jaszhix** [comment] 2017-08-24 07:42
It looks like both of your logs have a lot of errors/warnings from other applets and parts of Cinnamon's internal JS. Does the issue improve at all if you remove the applets showing errors in your logs?

**Comment by jaszhix** [comment] 2017-08-24 08:20
Backing up a little bit, what would help me to understand this is:
- What percentage of CPU resources is consumed by the Cinnamon thread
- What you were doing when you noticed the high CPU usage.
- Does it always have high usage from initialization to the point its noticed?

@Piiit This particular issue could be caused if you were dragging or pinning something, ```insert_child_at_index``` is used in the drag handlers. If you noticed there's a correlation there it might be somewhere to look. I can't reproduce it in VM or on my laptop though.

```
(cinnamon:2690): Clutter-CRITICAL **: clutter_actor_insert_child_at_index: assertion 'child->priv->parent == NULL' failed

(firefox:3124): Gtk-WARNING **: Attempting to read the recently used resources file at '/home/pemoser/.local/share/recently-used.xbel', but the parser failed: Datei »/home/pemoser/.local/share/recently-used.xbel« konnte nicht geöffnet werden: Keine Berechtigung.
Cinnamon warning: Log level 16: Attempting to read the recently used resources file at '/home/pemoser/.local/share/recently-used.xbel', but the parser failed: Datei »/home/pemoser/.local/share/recently-used.xbel« konnte nicht geöffnet werden: Keine Berechtigung.
Cjs-Message: JS WARNING: [/usr/share/cinnamon/js/ui/main.js 1231]: reference to undefined property Meta.KeyBindingAction.PANEL_MAIN_MENU
Cinnamon warning: Log level 8: Source ID 2066 was not found when attempting to remove it
Cjs-Message: JS LOG: About to start Cinnamon
```

@Protarios This part of the log looks like Wine is causing issues:

```
QXcbConnection: XCB error: 3 (BadWindow), sequence: 2178, resource id: 96468997, major code: 4 (DestroyWindow), minor code: 0
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Schreibtischdatei /usr/share/applications/caja-browser.desktop konnte nicht für Leistenstarter geöffnet werden
Schreibtischdatei /usr/share/applications/mate-terminal.desktop konnte nicht für Leistenstarter geöffnet werden

(nm-applet:1678): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(blueberry-tray.py:1879): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -8 and height 1
Cjs-Message: JS LOG: About to start Cinnamon
```

The last error is from network manager before your crash, and there's no telling what Wine is doing here.

Some of these issues are fixed on Cinnamon's master branch.

**Comment by Protarios** [comment] 2017-08-24 08:23
Also had the impression the problem somehow is connected to Wine.
The strange thing is, everything works perfect, if I disable Icing.

**Comment by jaszhix** [comment] 2017-08-24 08:32
ITM does demand its fair share of resources, but its sharing the same context with all the other applets. If one breaks in some way, it can affect other applets. Please provide more info, perf issues aren't very reproducible without describing what you're doing, and the software used.

**Comment by Piiit** [comment] 2017-08-24 12:26
@jaszhix Hi, I fixed the permission issue of the file `.local/share/recently-used.xbel`... that didn't fix the issue. I've removed all 3rd party applets except ITM for now. Let's see what happens... I'll report asap.

**Comment by jaszhix** [comment] 2017-08-25 20:08
I [trimmed down](https://github.com/linuxmint/cinnamon-spices-applets/pull/1178) the Lodash dependency, so maybe it will help. I am viewing the CPU usage percentage on the Cinnamon thread without division by cores, and unless I hover over a button (open the thumbnail menu), or do some kind of action, it stays at 0% for me. The highest I see it going to is 58% for a second, and it stays at 0% unless another action occurs.

**Comment by wladk** [comment] 2017-08-27 18:35
Same situation.
Distribution: Fedora 26
Cinnamon version: 3.4.6
Applet version: 5.3.3

I use double monitors configuration, on both monitors ITM installed (very nice to see which windows on which monitor presents). Since 10 minutes, proccess  "cinnamon" eats 17% of CPU time, window moving get completely slow, and after arount 15-20 minutes it hangs cinnamon (looks like muffin stops and not restarts, no window borders, keyboard doesnt work, only mouse). Only systemctl restart lightdm fix this from another tty.
If I remove ITM, there's no hanging nor muffin brakes.

On another computer I use ITM 2017-01-19, it works without problem (single monitor).

I will send tomorrow cinnamon glass and xsession errors.

**Comment by Z-42PO** [comment] 2017-08-31 15:08
Same problem here

Distribution: Linux Mint 18.2
Cinnamon version: 3.4.6
Applet version: 5.3.3

It's a bit better on Cinnamon 3.4.3 but still high CPU usage

My logs are attached
[log.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/1267532/log.txt)

**Comment by jaszhix** [comment] 2017-08-31 17:46
@Z-42PO Do you have hardware acceleration for video? The CPU shouldn't be involved in that.

I'll keep investigating this, I am seeing a little more activity with ITM on the panel after Cinnamon is running for a while. I'm not sure what it could be yet, but its probably a signal that has too much going on in its callback.

**Comment by Z-42PO** [comment] 2017-08-31 19:54
Yup, the CPU usage is not for the video (mpv) but for cinnamon. With ITM, mpv remain at ~20% CPU usage and cinnamon almost 90%.
Without ITM, there is no CPU usage for cinnamon (~5/10% max), and mpv is still at ~20%

**Comment by jaszhix** [comment] 2017-08-31 23:09
Okay, the consistent CPU usage I was noticing was from the multicore system monitor applet, removing it and its staying at 0% unless I interact with a window, or ITM. Would someone affected by this be able to provide their json settings in ~/.cinnamon/configs?

**Comment by jaszhix** [comment] 2017-08-31 23:53
I went ahead and logged every single method in ITM, to be sure nothing is continuously being called. There appears to be a loop getting stuck when its reloaded via Melange from a recursive actor.get_stage call, but adding, moving, removing the applet, or other applets doesn't trigger this. I also ran this in a 3.4 VM, and did some typical things like pinning apps and reordering them. The Cinnamon thread eventually idles at 0% on my host and the guest, from a range of 2-28% usage.

Here's the file if anyone wants to provide their glass.log, it may help identify what's getting called too much, or confirm my suspicion about the reload issue.

[IcingTaskManager@json-debug-1.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/1268790/IcingTaskManager.json-debug-1.zip)

**Comment by Z-42PO** [comment] 2017-09-11 21:02
Yes it's acting like being stuck in a loop, or doing too many call of something, overloading the CPU...

**Comment by jaszhix** [comment] 2017-09-11 21:23
Did you reload the applet?

**Comment by SerafDosSantos** [comment] 2017-09-11 22:14
Could the problem come from a kernel version or a Cinnamon? I've been having problems with some applets for some time and I'm not using the ITM applet.

**Comment by jaszhix** [comment] 2017-09-11 22:24
Its possible, I'm not reproducing the CPU issue at all anymore on a version of [CJS with upstream patches](https://github.com/linuxmint/cjs/compare/master...jaszhix:patch-2?expand=1). It has other issues though, like more random segfaults of a different variety.

**Comment by Z-42PO** [comment] 2017-09-15 21:37
I think it's fixed now. I'll make some test this week-end...

**Comment by BWhitten** [comment] 2017-09-25 18:15
Another 'same here', however I have found that the following steps brings my CPU to 100% 
- click the notes button in the systray to bring up the 'new note' option
- create a new note
- right click the note to bring up note menu
- move mouse up and down this menu hovering over 'about' 'configure', and 'remove'.

Then observe the lag and high CPU usage, it seems to be related to the initial menu from the systray being open whilst note menu is open.

**Comment by jaszhix** [comment] 2017-09-25 18:45
@BWhitten That would be an issue with Sticky Notes, you should let @collinss know about it.

**Comment by collinss** [comment] 2017-09-25 18:54
@BWhitten if you're seeing high cpu with the sticky notes applet, first check if the shadow behind notes is enabled in the settings. For some reason this causes high cpu on certain hardware. That's why I added the setting in the first place.

**Comment by BWhitten** [comment] 2017-09-25 19:21
@collinss Turning shadowing off has certainly helped in my case, even though it didn't look any different but I don't know where the shadow is applied. Cinnamon only hits 50% CPU usage now, still high but at least its more responsive now.

**Comment by collinss** [comment] 2017-09-25 23:25
@BWhitten The shadow is applied behind the individual notes to give them a bit of depth and make them look like they're hovering over whatever is below them.

**Comment by Z-42PO** [comment] 2017-10-08 21:39
Last version of ITM, no CPU problem anymore for me 👍

**Comment by jaszhix** [comment] 2017-10-09 05:15
Good to hear. I'll go ahead and close this since I'm not seeing any new reports.

**Closed by jaszhix** 2017-10-09 05:15 UTC
Labels: BUG
