### ISSUE TITLE
cinnamon crashing after last weather applet update

### ISSUE THREAD

**Issue by nalim** [linuxmint/cinnamon-spices-applets#1954] opened 2018-09-07 15:16 UTC
Fedora 28 64b

**Comment by nalim** [comment] 2018-09-07 15:27
temp fix: if I commented out line 182 in applet.js the applet works again.

line 182:
//Soup.Session.prototype.add_feature.call(_httpSession, new Soup.ProxyResolverDefault())

**Comment by jaszhix** [comment] 2018-09-07 15:50
Please attach ~/.xsession-errors after the crash occurs, and provide the info requested in the issue template.

**Comment by nalim** [comment] 2018-09-07 17:08
No ~/.xsession-errors file created. In system journal (journald) I can see cinnamon core dumped:

ep 07 19:04:15 u716 systemd-coredump[19821]: Process 4390 (cinnamon) of user 1000 dumped core.
                                              
                                              Stack trace of thread 4390:
                                              #0  0x00007f6a890112ee _GLOBAL__sub_I_Unified_cpp_js_src12.cpp (libmozjs-38.so)
                                              #1  0x00007f6b0588251a call_init.part.0 (ld-linux-x86-64.so.2)
                                              #2  0x00007f6b05882616 _dl_init (ld-linux-x86-64.so.2)
                                              #3  0x00007f6b058867bf dl_open_worker (ld-linux-x86-64.so.2)
                                              #4  0x00007f6afcd3296f _dl_catch_exception (libc.so.6)
                                              #5  0x00007f6b05886037 _dl_open (ld-linux-x86-64.so.2)
                                              #6  0x00007f6af9642006 dlopen_doit (libdl.so.2)
                                              #7  0x00007f6afcd3296f _dl_catch_exception (libc.so.6)
                                              #8  0x00007f6afcd329ff _dl_catch_error (libc.so.6)
                                              #9  0x00007f6af9642725 _dlerror_run (libdl.so.2)
                                              #10 0x00007f6af9642096 dlopen@@GLIBC_2.2.5 (libdl.so.2)
                                              #11 0x00007f6a8a3d6ae5 _ZN9libmodman14module_manager9load_fileENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb (libmodman.so.1)
                                              #12 0x00007f6a8a3d751b _ZN9libmodman14module_manager8load_dirENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb (libmodman.so.1)
                                              #13 0x00007f6a8a5e7011 n/a (libproxy.so.1)
                                              #14 0x00007f6a8a5e75ef px_proxy_factory_new (libproxy.so.1)
                                              #15 0x00007f6a8b1f16ed n/a (libgiolibproxy.so)
                                              #16 0x00007f6afd525f3a g_type_create_instance (libgobject-2.0.so.0)
                                              #17 0x00007f6afd5086c8 g_object_new_internal (libgobject-2.0.so.0)
                                              #18 0x00007f6afd509e15 g_object_new_with_properties (libgobject-2.0.so.0)
                                              #19 0x00007f6afd50a9d1 g_object_new (libgobject-2.0.so.0)
                                              #20 0x00007f6afd7ac5f1 try_implementation (libgio-2.0.so.0)
                                              #21 0x00007f6afd7ac738 _g_io_module_get_default (libgio-2.0.so.0)
                                              #22 0x00007f6b0417ed05 soup_proxy_resolver_default_constructed (libsoup-2.4.so.1)
                                              #23 0x00007f6afd5088fb g_object_new_internal (libgobject-2.0.so.0)
                                              #24 0x00007f6afd50a16d g_object_newv (libgobject-2.0.so.0)
                                              #25 0x00007f6b04c0b910 n/a (libcjs.so.0)

**Comment by nalim** [comment] 2018-09-07 17:12
{
    "uuid": "weather@mockturtl",
    "name": "Weather",
    "description": "View your local weather forecast",
    "max-instances": 3,
    "version": "1.14.0",
    "last-edited": 1536289505
}

cinnamon 3.8.8

Linux u716 4.17.19-200.fc28.x86_64 #1 SMP Fri Aug 24 15:47:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nalim** [comment] 2018-09-07 17:33
I have a stock Fedora 28 installation, I mean all packages are from stable rpm repository. I wouldn't spoil it with some non default rpms.

fedora 28 is using cjs 3.8.0 as of now

cjs rpm:

ame        : cjs
Epoch       : 1
Version     : 3.8.0
Release     : 1.fc28
Architecture: x86_64
Install Date: Tue 01 May 2018 19:16:34 CEST
Group       : Unspecified
Size        : 1022158
License     : MIT and (MPLv1.1 or GPLv2+ or LGPLv2+)
Signature   : RSA/SHA256, Tue 24 Apr 2018 21:52:57 CEST, Key ID e08e7e629db62fb1
Source RPM  : cjs-3.8.0-1.fc28.src.rpm
Build Date  : Mon 16 Apr 2018 17:04:39 CEST
Build Host  : buildvm-04.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/linuxmint/cjs
Bug URL     : https://bugz.fedoraproject.org/cjs
Summary     : Javascript Bindings for Cinnamon
Description :
Cjs allows using Cinnamon libraries from Javascript. It's based on the
Spidermonkey Javascript engine from Mozilla and the GObject introspection
framework.

**Comment by nalim** [comment] 2018-09-07 17:37
I'm  no expert but it looks to me libproxy library can't dynamically load some kind of dependency object file or library. I have no clue which one :-). Important is I have clean fedora 28 installation without any customization, all similar fedora 28 users are affected...

**Comment by nalim** [comment] 2018-09-07 17:38
Q: why was the line 182 commented out in the previous version of the applet? I suppose it has a reeason, hasn't it?

**Comment by jaszhix** [comment] 2018-09-07 17:41
I commented it out previously, but it wasn't related to a segfault. Not very familiar with how cjs is packaged there, but @leigh123linux might know.

**Comment by leigh123linux** [comment] 2018-09-07 21:56
@jaszhix I believe the issue is with a faulty mozjs38 package as all fedora cinnamon versions are built against mozjs52.

see https://bugzilla.redhat.com/show_bug.cgi?id=1573643

**Comment by Gr3q** [comment] 2020-07-25 06:08
@brownsr can you close this issue? This version of Fedora has been [EOL since mid-2019](https://bugzilla.redhat.com/show_bug.cgi?id=1573643)

**Closed** 2021-03-14 17:47 UTC
Labels: BUG
