### ISSUE TITLE
weather@mockturl - 

### ISSUE THREAD

**Issue by Rambo-Junior** [linuxmint/cinnamon-spices-applets#4649] opened 2023-01-18 22:58 UTC
```
 * Applet version - 3.2.11
 * Cinnamon version - 5.6.7
 * Distribution - Linux 5.15.0-58-generic 64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 GNU/Linux
 * Graphics hardware - 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 530 rev 06
```

**Notify author of applet**
@Gr3q

**Issue**

Stopped working, 

"Loadig..."

**Steps to reproduce**
N/A

**Expected behaviour**

![image](https://user-images.githubusercontent.com/63543220/213313597-61b28e98-4891-4beb-8bb4-d35e66734e86.png)

**Other information**

<details>
<summary>Relevant Logs</summary>

```
The contents of the file saved from the applet help page goes here
```

</details>

**Comment by Gr3q** [comment] 2023-01-19 09:27
Should I assume this is a duplicate of https://github.com/linuxmint/cinnamon-spices-applets/issues/4648? Could you provide logs?

**Comment by RamnoJunior** [comment] 2023-01-19 20:13
Gjs-Message: 21:08:23.164: JS LOG: [LookingGlass/info] [weather@mockturtl#15]: Removing applet instance...
Gjs-Message: 21:08:43.433: JS LOG: [LookingGlass/info] Installing settings for weather@mockturtl
Gjs-Message: 21:08:43.433: JS LOG: [LookingGlass/info] Settings successfully installed for weather@mockturtl
Gjs-Message: 21:08:43.484: JS LOG: [LookingGlass/info] [weather@mockturtl#22]: Internet access now available, resuming operations.
Gjs-Message: 21:08:53.681: JS LOG: [LookingGlass/info] [weather@mockturtl#22]: Error calling URL: Could not connect: Socket I/O timed out, null
Gjs-Message: 21:08:53.683: JS LOG: [LookingGlass/error] [weather@mockturtl#22]: Retrying in the next 15 seconds...
Gjs-Message: 21:08:53.684: JS LOG: [LookingGlass/info] [weather@mockturtl#22]: App is currently refreshing, refresh skipped in main loop
Gjs-Message: 21:09:11.458: JS LOG: [LookingGlass/info] [weather@mockturtl#22]: Error calling URL: Could not connect: Socket I/O timed out, null
Gjs-Message: 21:09:11.458: JS LOG: [LookingGlass/error] [weather@mockturtl#22]: Retrying in the next 15 seconds...
Gjs-Message: 21:09:23.148: JS LOG: [LookingGlass/info] Reloading applet: weather@mockturtl/22
Gjs-Message: 21:09:23.149: JS LOG: [LookingGlass/info] [weather@mockturtl#22]: Removing applet instance...
Gjs-Message: 21:09:23.229: JS LOG: [LookingGlass/info] [weather@mockturtl#22]: Internet access now available, resuming operations.
Gjs-Message: 21:09:23.244: JS LOG: [LookingGlass/info] Loaded applet weather@mockturtl in 86 ms
Gjs-Message: 21:09:33.279: JS LOG: [LookingGlass/info] [weather@mockturtl#22]: API full response: undefined
Gjs-Message: 21:09:33.280: JS LOG: [LookingGlass/info] [weather@mockturtl#22]: Error calling URL: Could not connect: Socket I/O timed out, null
Gjs-Message: 21:09:33.282: JS LOG: [LookingGlass/info] [weather@mockturtl#22]: User facing Error received, error: {
Gjs-Message: 21:09:33.284: JS LOG: [LookingGlass/error] [weather@mockturtl#22]: Retrying in the next 15 seconds...
Gjs-Message: 21:09:33.286: JS LOG: [LookingGlass/info] [weather@mockturtl#22]: App is currently refreshing, refresh skipped in main loop
Gjs-Message: 21:09:40.275: JS LOG: [LookingGlass/info] [weather@mockturtl#22]: On location storage callback called, number of locations now 0
Gjs-Message: 21:09:40.277: JS LOG: [LookingGlass/info] [weather@mockturtl#22]: On location storage callback called, number of locations now 0
Gjs-Message: 21:09:40.278: JS LOG: [LookingGlass/info] [weather@mockturtl#22]: On location storage callback called, number of locations now 0
Gjs-Message: 21:09:40.279: JS LOG: [LookingGlass/info] [weather@mockturtl#22]: On location storage callback called, number of locations now 0rambojunior@ThinkPad-T470s:~$

**Comment by RamnoJunior** [comment] 2023-01-19 20:14
Yes, I am afraid it is the same, please see logs above and yes if I switch to manual it works. 

Any hint what can cause this? 

Thank you

**Comment by RamnoJunior** [comment] 2023-01-19 20:17
LOL most nézem, hogy akár magyarul is írhatnék :)

**Comment by Gr3q** [comment] 2023-01-24 09:38
Az egyetlen tippem hogy ip-api.com blokkol magyarországon valahol. Nem nagyon tudom kideríteni hacsak nem van valami közös tényező közted és @meszaros-lajos-gyorgy között.

My only guess is ip-api.com is blocking IPs somewhere in Hungary. If I don't know what is the common location/thing/reason it does it I will not be able to debug it. Maybe I should change to a different service.

**Comment by Rambo-Junior** [comment] 2023-01-24 09:56
Igazad van, teszteltem VPN-el pl Brüsszelből és úgy simán megy. 

You are right, I did test it with VPN from Brussels and it works. 
I did switched as a test for MET Norway and still the same issue without VPN.

**Comment by Gr3q** [comment] 2023-01-24 21:13
Ki tudod kapcsolni az `Automcatic Location`t és akkor mind menni fog amíg ki nem derítem miért van blokkolva.

**Comment by Rambo-Junior** [comment] 2023-01-27 12:22
Köszi, ezt csináltam. Remélem sikerül rájönni mi okozhatja ezt a problémát

**Comment by Rambo-Junior** [comment] 2023-06-14 16:18
I found out (for me at least) pi-hole blocked the following URL
`get.geojs.io`

since then it works

**Closed** 2023-07-21 12:21 UTC
