### ISSUE TITLE
translation in Cinnamenu incomplete

### ISSUE THREAD

**Issue by oldtomdevel** [linuxmint/cinnamon-spices-applets#3623] opened 2021-02-23 12:29 UTC
Cinnamenu (Cinnamenu@json) V4.12.6

Having updated to the above mentioned version, I noticed that not all text is translated e.g. "All applications" and some text in settings.
I tried to fix it by editing the file 
`~/.local/share/cinnamon/applets/Cinnamenu@json/po/de.po`
i.e. I added e.g. the lines
`msgid "All applications"`
`msgstr "Alle Anwendungen"`.
However, it does not work.
I cannot judge why.
However, please check if all text is intended to be translated.
Moreover, please advise (maybe as a tooltip in settings?) how to adapt the translations yourself.

**Comment by NikoKrause** [comment] 2021-02-23 12:43
The German translation of Cinnamenu is indeed incomplete: https://github.com/linuxmint/cinnamon-spices-applets/blob/translation-status-tables/.translation-tables/tables/Cinnamenu@json.md

If you want to help completing the translation, I suggest to use the application `poedit`.

You can find instructions here: https://github.com/NikoKrause/CinnVIIStarkMenu/issues/19

If you have any questions, do not hesitate to ask.

**Comment by oldtomdevel** [comment] 2021-02-23 19:17
The fact that the German translation is incomplete is just a minor problem as this could be completed quite easily.
However, the bigger problem seems to be that some translations are correctly given in the file `de.po` but without any effect.

I checked manually the files`de.po` and `Cinnamenu.pot` and found the correct translations. I tried the application `poedit` and it also stated the translation correctly. However, the applet does not give the translation but the English original. This affects e.g. the entry "Favorite apps" in the menu. Therefore, it seems to me that there could be some bug in the applet (it behaves as if it skipped the search for translation in some cases).

This reminds me of `[linuxmint/cinnamon-spices-applets] Cinnamenu@json - bug (#3203)` which appeared sometimes (it was unfortunately not possible to find out the trigger of the bug in order to reproduce it).

**Comment by NikoKrause** [comment] 2021-02-23 19:43
I checked the German translation for `Favorite apps` and it's not translated.
There's another string `Favorite Apps`, which IS translated.

You have to know, that translation strings are case sensitive. Those two strings are completely different to the translation function.
Do you have maybe other examples, which I should have a look at? If not, I would say, that the Cinnamenu is just missing translations. I would be happy to see a contribution from you helping to get it translated :)

If you need help or have any questions on how to contribute, do not hesitate to ask.

**Comment by oldtomdevel** [comment] 2021-02-24 08:05
It is true that the de.po file contains "Favorite Apps" instead of the original English string "Favorite apps" which is given in Cinnamenu. Similarly, the po file contains "All Applications" whereas it should contain "All applications" which again is given in Cinnamenu.

As I have understood the po file structure, it works as follows. The program looks for the original string as an msgid entry and prints the following msgstr entry instead. Therefore, I would expect to get the translation working by just editing the po file as follows: change the existing `msgid "Favorite Apps"` `msgstr "Favoriten"` into  `msgid "Favorite apps"` `msgstr "Favoriten"`. But this does not work. Appearently, the program does not look for an translation of "Favorite apps".

**Comment by NikoKrause** [comment] 2021-02-24 08:32
The applet doesn't look in de.po for translations. It looks in the compiled version, which has an `.mo` ending and is stored in a specific place in your home directory.

IIf you want to test your changes you need to "install" your changes.

See section "Testing your translations" here NikoKrause/CinnVIIStarkMenu#19

**Comment by oldtomdevel** [comment] 2021-02-24 12:03
When I follow your reference, I get an error message as follows (copied from terminal):

may@Asterix:~/.local/share/cinnamon/applets/Cinnamenu@json$ cinnamon-json-makepot -i
/usr/bin/cinnamon-xlet-makepot:49: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if rel_root is '.':
/usr/bin/cinnamon-xlet-makepot:156: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if files_installed is 0:
/usr/bin/cinnamon-xlet-makepot:173: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if files_removed is 0:
installed 29 files

I have an standard installation of LM20 Cin 64bit.

**Comment by NikoKrause** [comment] 2021-02-24 12:28
It seems to be an issue in Mint 20, which has been fixed in Mint 20.1.

https://github.com/linuxmint/cinnamon/commit/be252d3f34f0d6e77982b6eaf3b7ddc0b8bc867e#diff-023e2185901ddc9737faaa709de5a1ddf4ffc86498acbc1a9d3bcd0b7a367591

Your output says `installed 29 files` anyway. Have you checked if the translations were applied anyway?

**Comment by oldtomdevel** [comment] 2021-02-24 18:06
It seems to be true that the above mentioned error message can be ignored.
However, here are the results of my experiments.

I edited the file `~/.local/share/cinnamon/applets/Cinnamenu@json/po/de.po` i.e. I completed some translations.
Afterward I followed the above referenced document to test the new translations i.e.
- Open a terminal in the directory `~/.local/share/cinnamon/applets/Cinnamenu@json` where the file `metadata.json` is saved.
- Type in the command `cinnamon-json-makepot -i` to install the existing translations (i.e. the .po files). Doing that ignore the error messages.
- Restart Cinnamon: CTRL+ALT+ESC.

Having done all that, all text that appears in the settings dialogue of Cinnamenu and that has been explicitly mentioned in the `de.po` file is now translated as intended. However, the categories "All Applications" and "Favorite Apps" in Cinnamenu itself are not translated. I have included "All Applications" and "All applications" as well in the `de.po` file, also "Favorite apps" and "Favorite Apps". Those texts appear in the settings dialogue as well (where to set the starting category when opening the menu), there the texts are translated as intended but the menu categories (with the same original text) are not.

As the missing translations for the two categories were my starting point, I firstly did not realize that editing the `de.po` file changes the text within the settings dialogue.

I think the missing translations for the two categories are not caused by the incomplete `de.po` file but by some other effect.

**Comment by NikoKrause** [comment] 2021-02-24 18:12
Can you add some screenshots?

**Comment by NikoKrause** [comment] 2021-02-24 19:42
Ok, no need for screenshots.
I could reproduce the issue and found the bug.

**Closed** 2021-02-24 20:41 UTC

**Comment by fredcw** [comment] 2021-02-25 02:47
The reason there's "All Applications" and "All applications" etc. is because I made changes to the 4.0 version of cinnamenu but left the 3.2 version alone which I guess is an oversight. I'll make some changes to the 3.2 version so there isn't so many similar but different strings.
