### ISSUE TITLE
radio icon

### ISSUE THREAD

**Issue by dave841** [linuxmint/cinnamon-spices-applets#2843] opened 2020-02-02 23:10 UTC
radio icon

```
 *  Radio Icon applet / Updated on 2019-11-29 18:02:10    
 * cinnamon 19.3  4.4.8
 *  linux mint kernel 5.3.0.28-generic
 * rx 580 radeon amd/ati ellesmere pulse sapphire
* Intel core I7 K875 overclock 2.93ghz x4 
* mem corsair 16.0 gb 
* Hard drives 3394.5 GB samsung rpm 5400
   
 

<!-- Author list: https://github.com/linuxmint/cinnamon-spices-applets/blob/master/.github
      radio@driglu4it //// 
   **Notify author of applet**
       Driglu4it 

**Issue**
just want to ask a question its not really a issue but how do i change the icon thats on the radio.
take a screen shot of the icon on the top right corner. am sorry for asking for help but there somethings need to know about linux.lol



**Steps to reproduce**
*


**Expected behaviour**

*

**Other information**
*
![Screenshot from 2020-02-02 23-07-46](https://user-images.githubusercontent.com/60449271/73616912-f9a54380-4610-11ea-9a9f-94fdf2e85e5f.png)

**Comment by claudiux** [comment] 2020-02-03 12:10
@dave841 (Please use the "Preview" tab and triple-quotes to format your message.)

Modify or change `~/.local/share/cinnamon/applets/radio@driglu4it/icons/radio.svg`. This must be a .svg file. You can use Inkscape to create of modify a svg-format icon.

**Comment by dave841** [comment] 2020-02-03 12:25
ok thank you

**Comment by Padre2** [comment] 2020-02-12 06:00
@driglu4it  @claudiux 
I'm not sure this is connected, but I have just installed Radio++ on Ubuntu Cinnamon Remix
Ubuntu 19.10 
Cinnamon 4.0.10 (same version as referred to above by @dave841 ).
Radio++ version 2019-11-29 18:02 UTC
The icon displayed in the panel is a simple circle, not the usual radio icon.
In Arch with Cinnamon 4.4.8, the Radio++ version is 2019-11-30 01:02:10 with the usual icon.
Checking the files on Ubuntu, I could not find where the circle icon comes from.
I presume that Ubuntu downloads the earlier version because the Cinnamon version is much earlier, although I didn't discover anything indicating how from the metadata.json file.

**Comment by Odyseus** [comment] 2020-02-12 06:57
Hello, everybody.

> I could not find where the circle icon comes from.

@Padre2: The circle comes from your icon theme. The applet icon is set a second time after initialization [here](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/radio%40driglu4it/files/radio%40driglu4it/applet.js#L41), and this time it's set by name instead of by path.

Your icon theme has the icon named `radio` as in the checkable menu item (![radio](https://user-images.githubusercontent.com/3822556/74310188-54464a00-4d4b-11ea-9c78-fb3b31aff89c.png)), not radio the electronic device (![library-internet-radio](https://user-images.githubusercontent.com/3822556/74310271-92dc0480-4d4b-11ea-9958-46b1ad1c27ff.png)).

**Comment by Padre2** [comment] 2020-02-13 04:06
@Odyseus Thank you for pointing out the cause.
@claudiux  Thank you for applying the modification.
Btw, my drive with the Ubuntu Cinnamon Remix just crashed so I cannot check any further at this time.

**Comment by claudiux** [comment] 2020-02-14 23:10
@Odyseus @Padre2 @dave841 Is this version suiting you? #2858

**Comment by Odyseus** [comment] 2020-02-14 23:23
Hello, @claudiux.

I can't test it fully since I don't use `moc` nor the latest Cinnamon version. **Padre2** and **dave841** might give you better feedback.

**Comment by dave841** [comment] 2020-02-14 23:37
hello dave841

i have tryed to change the radio icon and it is still the same. my radio icon symbol is a early radio icon and did both and did not not its in my second panel at the top here is a screen short of my desktop the radio icon is at the far right corner HERE IT IS LOOK CAREFULLY ITS SMALL
![Screenshot from 2020-02-14 23-34-49](https://user-images.githubusercontent.com/60449271/74576474-d53b5680-4f82-11ea-869a-961875c61c06.png)
er

**Comment by Padre2** [comment] 2020-02-17 15:33
@dave841 
If you want a coloured icon, open the icon.png file in Inkscape and save as radio.svg.
You can then put it into the icons directory to replace the old SVG icon and it should display.

**Comment by dave841** [comment] 2020-02-17 19:02
ok thank you

**Comment by Padre2** [comment] 2020-02-19 03:51
> @dave841  
> If you want a coloured icon, open the icon.png file in Inkscape and save as radio.svg.
> You can then put it into the icons directory to replace the old SVG icon and it should display.

Sorry, I was not paying attention to the details. For it to display in the panel, you should  rename the old icon as radioapplet-symbolic.svg.old and  save the coloured icon as radioapplet-symbolic.svg

**Comment by dave841** [comment] 2020-02-27 19:26
thank you padre2. i have been able to sort out the radioapplet symbol.svg. All i had to do was update the app and gives you a option for the icons, i will show you a pic of it now
![Screenshot from 2020-02-27 19-25-26](https://user-images.githubusercontent.com/60449271/75479173-f9d9fa00-5996-11ea-8235-7f520c57d04c.png)

**Comment by claudiux** [comment] 2020-06-12 15:23
@dave841 Can you close this issue, please?

**Closed** 2020-06-15 16:18 UTC
