### ISSUE TITLE
multicore-sys-monitor@ccadeptic23: When hovering mouse into panel and then from panel into applet, panel auto-hide stops working

### ISSUE THREAD

**Issue by patrr** [linuxmint/cinnamon-spices-applets#6384] opened 2024-09-07 16:40 UTC
### Applet version/Build date

Version 1.9.6 (2024-07-30 17:01:22)

### Cinnamon version

Cinnamon 6.0.4

### Distribution

Linux Mint 21.3 Cinnamon

### Graphics hardware *and* driver used

Intel Corporation Haswell-ULT Integrated Graphics Controller

### Applet name and maintainer

multicore-sys-monitor@ccadeptic23 @claudiux

### What happened?

I am a long time user of your great applet.
Thank you!

I think I found a minor bug.

With no window open, hovering mouse into the panel and then from panel into the applet, causes panel auto-hide to stop working (or maybe to fall into the 'intelligently hide panel' mode).
Hovering again the mouse on the applet causes the panel to auto-hide again.
I can reproduce this behaviour all the times.
See enclosed screencast.

### Other information

https://github.com/user-attachments/assets/2b5a75a2-f654-4b9c-8c32-1a3150ea8c3c

**Comment by claudiux** [comment] 2024-09-07 21:43
@patrr 
I can't reproduce this issue on Cinnamon 6.2.9 (LM22).
I'll make some tests on Cinnamon 6.0.4.

**Comment by claudiux** [comment] 2024-09-07 22:06
@patrr 
I can reproduce this issue on Cinnamon 6.0.4 (LM21.3).
I'll compare the differences between the both ways of hiding the panel.
But the best way is to upgrade to LM22.

**Comment by patrr** [comment] 2024-09-08 09:30
Thanks for the quick answer.
I'll upgrade to LM22 when LM21.3 will prompt me to do so from the update manager and the upgrade process will hopingly have been tuned better.
This because on a test machine of mine I could not upgrade smoothly with the standalone upgrader mintupgrade.

**Comment by claudiux** [comment] 2024-09-08 09:38
I have successfully upgraded LM on many computer with:
```
apt install --reinstall mintupgrade
sudo mintupgrade
```

It is certain that this issue does not stem from my code. So I'm closing it.

**Closed by claudiux** 2024-09-08 09:38 UTC
Labels: BUG
