### ISSUE TITLE
Cinnamon crash because applet

### ISSUE THREAD

**Issue by Heidistein** [linuxmint/cinnamon-spices-applets#3416] opened 2021-01-08 10:51 UTC
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
Version 1.6.4 (2020-10-03 13:52:17)
 * Cinnamon version (cinnamon --version)
 Cinnamon 4.8.3
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 Fedora-33
 * Graphics hardware *and* driver used
 00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
I beleve the modesetting driver is used
 * Snippet or attachment of ~/.cinnamon/glass.log
 This file does not exist... :-/
 * Snippet or attachment of ~/.xsession-errors
 Cjs-Message: 11:48:18.958: JS LOG: [LookingGlass/info] Installing settings for sysmonitor@orcus
Cjs-Message: 11:48:18.959: JS LOG: [LookingGlass/info] Settings successfully installed for sysmonitor@orcus
Cjs-Message: 11:48:18.965: JS LOG: [LookingGlass/error] assignment to undeclared variable info
Cjs-Message: 11:48:18.970: JS LOG: [LookingGlass/info] Loaded applet sysmonitor@orcus in 47 ms
**
Cjs:ERROR:../gi/function.cpp:1063:void uninit_cached_function_data(Function*): assertion failed: (function->info && "Don't know how to free cache without GI info")
jan 08 11:48:25 anuc systemd-coredump[11415]: Process 5444 (cinnamon) of user 1000 dumped core.
                                              
                                              Stack trace of thread 5457:
                                              #0  0x00007fd8fc5829d5 raise (libc.so.6 + 0x3d9d5)
                                              #1  0x00007fd8fc56b8a4 abort (libc.so.6 + 0x268a4)
                                              #2  0x00007fd8fcadfb6c g_assertion_message.cold (libglib-2.0.so.0 + 0x1db6c)
                                              #3  0x00007fd8fcb3a26f g_assertion_message_expr (libglib-2.0.so.0 + 0x7826f)
                                              #4  0x00007fd8fc3ed7ce _ZL27uninit_cached_function_dataP8Function.lto_priv.0 (libcjs.so.0 + 0x3a7ce)
                                              #5  0x00007fd8fc3ed7ed _ZL17function_finalizeP8JSFreeOpP8JSObject (libcjs.so.0 + 0x3a7ed)
                                              #6  0x00007fd8f96d1698 _Z19FinalizeTypedArenasI8JSObjectEbP8JSFreeOpPPN2js2gc5ArenaERNS4_15SortedArenaListENS4_9AllocKindERNS3_11SliceBudgetE.lto_priv.0 (libmozjs-78.so.0 + 0x5a3698)
                                              #7  0x00007fd8f96b44cb _ZN2js2gc10ArenaLists18backgroundFinalizeEP8JSFreeOpPNS0_5ArenaEPS5_ (libmozjs-78.so.0 + 0x5864cb)
                                              #8  0x00007fd8f96b5d77 _ZN2js2gc19BackgroundSweepTask3runEv (libmozjs-78.so.0 + 0x587d77)
                                              #9  0x00007fd8f96c0387 _ZN2js14GCParallelTask7runTaskEv (libmozjs-78.so.0 + 0x592387)
                                              #10 0x00007fd8f938c8b8 _ZN2js12HelperThread24handleGCParallelWorkloadERNS_25AutoLockHelperThreadStateE (libmozjs-78.so.0 + 0x25e8b8)
                                              #11 0x00007fd8f938d744 _ZN2js12HelperThread10ThreadMainEPv (libmozjs-78.so.0 + 0x25f744)
                                              #12 0x00007fd8f938dad9 _ZN2js6detail16ThreadTrampolineIRFvPvEJPNS_12HelperThreadEEE5StartES2_ (libmozjs-78.so.0 + 0x25fad9)
                                              #13 0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #14 0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)
                                              
                                              Stack trace of thread 5452:
                                              #0  0x00007fd8fb4c76c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                                              #1  0x00007fd8f50b5beb util_queue_thread_func (iris_dri.so + 0x49dbeb)
                                              #2  0x00007fd8f50b56ab impl_thrd_routine (iris_dri.so + 0x49d6ab)
                                              #3  0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #4  0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)
                                              
                                              Stack trace of thread 5444:
                                              #0  0x00007fd8fb4c76c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                                              #1  0x00007fd8f99f44ed _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (libmozjs-78.so.0 + 0x8c64ed)
                                              #2  0x00007fd8f99f6455 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so.0 + 0x8c8455)
                                              #3  0x00007fd8f96c0f65 _ZN2js14GCParallelTask4joinEv (libmozjs-78.so.0 + 0x592f65)
                                              #4  0x00007fd8f96c4ced _ZN2js2gc9GCRuntime16incrementalSliceERNS_11SliceBudgetERKN7mozilla5MaybeI18JSGCInvocationKindEEN2JS8GCReasonERNS0_13AutoGCSessionE (libmozjs-78.so.0 + 0x596ced)
                                              #5  0x00007fd8f96ca1fc _ZN2js2gc9GCRuntime7gcCycleEbNS_11SliceBudgetERKN7mozilla5MaybeI18JSGCInvocationKindEEN2JS8GCReasonE (libmozjs-78.so.0 + 0x59c1fc)
                                              #6  0x00007fd8f96cbc32 _ZN2js2gc9GCRuntime7collectEbNS_11SliceBudgetERKN7mozilla5MaybeI18JSGCInvocationKindEEN2JS8GCReasonE (libmozjs-78.so.0 + 0x59dc32)
                                              #7  0x00007fd8f92e9fd1 _Z5JS_GCP9JSContextN2JS8GCReasonE (libmozjs-78.so.0 + 0x1bbfd1)
                                              #8  0x00007fd8fc40aa13 _ZN17GjsContextPrivate20trigger_gc_if_neededEPv (libcjs.so.0 + 0x57a13)
                                              #9  0x00007fd8fcb16041 g_timeout_dispatch (libglib-2.0.so.0 + 0x54041)
                                              #10 0x00007fd8fcb1596f g_main_context_dispatch (libglib-2.0.so.0 + 0x5396f)
                                              #11 0x00007fd8fcb67758 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa5758)
                                              #12 0x00007fd8fcb15033 g_main_loop_run (libglib-2.0.so.0 + 0x53033)
                                              #13 0x00007fd8fc7731f2 meta_run (libmuffin.so.0 + 0x631f2)
                                              #14 0x0000561e4b2d7acc main (cinnamon + 0x2acc)
                                              #15 0x00007fd8fc56d1e2 __libc_start_main (libc.so.6 + 0x281e2)
                                              #16 0x0000561e4b2d7bee _start (cinnamon + 0x2bee)
                                              
                                              Stack trace of thread 5448:
                                              #0  0x00007fd8fc63b80f __poll (libc.so.6 + 0xf680f)
                                              #1  0x00007fd8fcb676f6 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa56f6)
                                              #2  0x00007fd8fcb15033 g_main_loop_run (libglib-2.0.so.0 + 0x53033)
                                              #3  0x00007fd8fcd5dd1a gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x10fd1a)
                                              #4  0x00007fd8fcb432b2 g_thread_proxy (libglib-2.0.so.0 + 0x812b2)
                                              #5  0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #6  0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)
                                              
                                              Stack trace of thread 5449:
                                              #0  0x00007fd8fc63b80f __poll (libc.so.6 + 0xf680f)
                                              #1  0x00007fd8fcb676f6 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa56f6)
                                              #2  0x00007fd8fcb12d43 g_main_context_iteration (libglib-2.0.so.0 + 0x50d43)
                                              #3  0x00007fd8f74d464d dconf_gdbus_worker_thread (libdconfsettings.so + 0x664d)
                                              #4  0x00007fd8fcb432b2 g_thread_proxy (libglib-2.0.so.0 + 0x812b2)
                                              #5  0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #6  0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)
                                              
                                              Stack trace of thread 11357:
                                              #0  0x00007fd8fc64130d syscall (libc.so.6 + 0xfc30d)
                                              #1  0x00007fd8fcb622ec g_cond_wait_until (libglib-2.0.so.0 + 0xa02ec)
                                              #2  0x00007fd8fcae63c1 g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x243c1)
                                              #3  0x00007fd8fcae6546 g_async_queue_timeout_pop (libglib-2.0.so.0 + 0x24546)
                                              #4  0x00007fd8fcb45ef9 g_thread_pool_thread_proxy.lto_priv.0 (libglib-2.0.so.0 + 0x83ef9)
                                              #5  0x00007fd8fcb432b2 g_thread_proxy (libglib-2.0.so.0 + 0x812b2)
                                              #6  0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #7  0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)
                                              
                                              Stack trace of thread 5450:
                                              #0  0x00007fd8fb4c76c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                                              #1  0x00007fd8f50b5beb util_queue_thread_func (iris_dri.so + 0x49dbeb)
                                              #2  0x00007fd8f50b56ab impl_thrd_routine (iris_dri.so + 0x49d6ab)
                                              #3  0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #4  0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)
                                              
                                              Stack trace of thread 5453:
                                              #0  0x00007fd8fb4c76c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                                              #1  0x00007fd8f50b5beb util_queue_thread_func (iris_dri.so + 0x49dbeb)
                                              #2  0x00007fd8f50b56ab impl_thrd_routine (iris_dri.so + 0x49d6ab)
                                              #3  0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #4  0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)
                                              
                                              Stack trace of thread 5458:
                                              #0  0x00007fd8fb4c76c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                                              #1  0x00007fd8f99f44ed _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (libmozjs-78.so.0 + 0x8c64ed)
                                              #2  0x00007fd8f99f6455 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so.0 + 0x8c8455)
                                              #3  0x00007fd8f938d6b6 _ZN2js12HelperThread10ThreadMainEPv (libmozjs-78.so.0 + 0x25f6b6)
                                              #4  0x00007fd8f938dad9 _ZN2js6detail16ThreadTrampolineIRFvPvEJPNS_12HelperThreadEEE5StartES2_ (libmozjs-78.so.0 + 0x25fad9)
                                              #5  0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #6  0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)
                                              
                                              Stack trace of thread 5454:
                                              #0  0x00007fd8fb4c76c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                                              #1  0x00007fd8f99f44ed _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (libmozjs-78.so.0 + 0x8c64ed)
                                              #2  0x00007fd8f99f6455 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so.0 + 0x8c8455)
                                              #3  0x00007fd8f938d6b6 _ZN2js12HelperThread10ThreadMainEPv (libmozjs-78.so.0 + 0x25f6b6)
                                              #4  0x00007fd8f938dad9 _ZN2js6detail16ThreadTrampolineIRFvPvEJPNS_12HelperThreadEEE5StartES2_ (libmozjs-78.so.0 + 0x25fad9)
                                              #5  0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #6  0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)
                                              
                                              Stack trace of thread 5460:
                                              #0  0x00007fd8fb4c76c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                                              #1  0x00007fd8f99f44ed _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (libmozjs-78.so.0 + 0x8c64ed)
                                              #2  0x00007fd8f99f6455 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so.0 + 0x8c8455)
                                              #3  0x00007fd8f938d6b6 _ZN2js12HelperThread10ThreadMainEPv (libmozjs-78.so.0 + 0x25f6b6)
                                              #4  0x00007fd8f938dad9 _ZN2js6detail16ThreadTrampolineIRFvPvEJPNS_12HelperThreadEEE5StartES2_ (libmozjs-78.so.0 + 0x25fad9)
                                              #5  0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #6  0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)
                                              
                                              Stack trace of thread 5461:
                                              #0  0x00007fd8fb4c76c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                                              #1  0x00007fd8f99f44ed _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (libmozjs-78.so.0 + 0x8c64ed)
                                              #2  0x00007fd8f99f6455 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so.0 + 0x8c8455)
                                              #3  0x00007fd8f938d6b6 _ZN2js12HelperThread10ThreadMainEPv (libmozjs-78.so.0 + 0x25f6b6)
                                              #4  0x00007fd8f938dad9 _ZN2js6detail16ThreadTrampolineIRFvPvEJPNS_12HelperThreadEEE5StartES2_ (libmozjs-78.so.0 + 0x25fad9)
                                              #5  0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #6  0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)
                                              
                                              Stack trace of thread 5459:
                                              #0  0x00007fd8fb4c76c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                                              #1  0x00007fd8f99f44ed _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (libmozjs-78.so.0 + 0x8c64ed)
                                              #2  0x00007fd8f99f6455 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so.0 + 0x8c8455)
                                              #3  0x00007fd8f938d6b6 _ZN2js12HelperThread10ThreadMainEPv (libmozjs-78.so.0 + 0x25f6b6)
                                              #4  0x00007fd8f938dad9 _ZN2js6detail16ThreadTrampolineIRFvPvEJPNS_12HelperThreadEEE5StartES2_ (libmozjs-78.so.0 + 0x25fad9)
                                              #5  0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #6  0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)
                                              Stack trace of thread 5455:
                                              #0  0x00007fd8fb4c76c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                                              #1  0x00007fd8f99f44ed _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (libmozjs-78.so.0 + 0x8c64ed)
                                              #2  0x00007fd8f99f6455 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so.0 + 0x8c8455)
                                              #3  0x00007fd8f938d6b6 _ZN2js12HelperThread10ThreadMainEPv (libmozjs-78.so.0 + 0x25f6b6)
                                              #4  0x00007fd8f938dad9 _ZN2js6detail16ThreadTrampolineIRFvPvEJPNS_12HelperThreadEEE5StartES2_ (libmozjs-78.so.0 + 0x25fad9)
                                              #5  0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #6  0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)
                                              
                                              Stack trace of thread 5451:
                                              #0  0x00007fd8fb4c76c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                                              #1  0x00007fd8f50b5beb util_queue_thread_func (iris_dri.so + 0x49dbeb)
                                              #2  0x00007fd8f50b56ab impl_thrd_routine (iris_dri.so + 0x49d6ab)
                                              #3  0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #4  0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)
                                              
                                              Stack trace of thread 5456:
                                              #0  0x00007fd8fb4c76c2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6c2)
                                              #1  0x00007fd8f99f44ed _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (libmozjs-78.so.0 + 0x8c64ed)
                                              #2  0x00007fd8f99f6455 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so.0 + 0x8c8455)
                                              #3  0x00007fd8f938d6b6 _ZN2js12HelperThread10ThreadMainEPv (libmozjs-78.so.0 + 0x25f6b6)
                                              #4  0x00007fd8f938dad9 _ZN2js6detail16ThreadTrampolineIRFvPvEJPNS_12HelperThreadEEE5StartES2_ (libmozjs-78.so.0 + 0x25fad9)
                                              #5  0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #6  0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)
                                              
                                              Stack trace of thread 5447:
                                              #0  0x00007fd8fc63b80f __poll (libc.so.6 + 0xf680f)
                                              #1  0x00007fd8fcb676f6 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa56f6)
                                              #2  0x00007fd8fcb12d43 g_main_context_iteration (libglib-2.0.so.0 + 0x50d43)
                                              #3  0x00007fd8fcb14961 glib_worker_main (libglib-2.0.so.0 + 0x52961)
                                              #4  0x00007fd8fcb432b2 g_thread_proxy (libglib-2.0.so.0 + 0x812b2)
                                              #5  0x00007fd8fb4c13f9 start_thread (libpthread.so.0 + 0x93f9)
                                              #6  0x00007fd8fc646903 __clone (libc.so.6 + 0x101903)


 ```

**Notify author of applet**
@

**Issue**
Crash seconds after loading applet

**Steps to reproduce**

Justadd applet

**Expected behaviour**

**Other information**

**Comment by NikoKrause** [comment] 2021-01-08 16:01
Which applet?

**Comment by peppschmier67** [comment] 2021-01-09 20:40
sysmonitor@orcus crashes when you enable the network traffic monitor .. i think the problem i quite similar to 
https://github.com/linuxmint/cinnamon-spices-applets/issues/3350

please take a look

**Comment by NikoKrause** [comment] 2021-01-10 08:41
@OrcusCZ

**Comment by dajusc** [comment] 2021-01-12 09:50
This bug also affects Linux Mint 20.1 which comes with Cinnamon 4.8.5 (see https://blog.linuxmint.com/?p=4011#comment-176760).

**Comment by leigh123linux** [comment] 2021-01-12 12:24
I can't reproduce this using cjs-4.8.2

**Comment by kelebek333** [comment] 2021-01-12 16:14
The issue may have been resolved with the latest cjs update. Could you update CJS to 4.8.2 version?

https://github.com/linuxmint/cinnamon-spices-applets/issues/3350#issuecomment-758761652

**Comment by dajusc** [comment] 2021-01-12 16:36
Yes, I can confirm this as well. On Linux Mint 20.1 the problem disappeared with the update to CJS 4.8.2 that came today.

**Closed** 2021-01-12 16:35 UTC

**Comment by ehtron** [comment] 2021-01-12 21:29
Works on cjs 4.8.2 
but ...
does not survive the cinnamon restart... must disable and enable again

**Comment by Heidistein** [comment] 2021-01-15 07:46
today I notices an update (Version 1.6.5 (2021-01-13 17:48:16)), which still let Cinnamon crash, with a very similar stacktrace.

**Comment by dajusc** [comment] 2021-01-15 09:01
Which CJS-version do you have? 

On my Systems the sysmonitor@orcus works/worked fine with the following combinations:
-  sysmonitor v1.6.4 + CJS 4.6.0
-  sysmonitor v1.6.5 + CJS 4.6.0
-  sysmonitor v1.6.5 + CJS 4.8.2

**Comment by Heidistein** [comment] 2021-01-15 09:17
cjs-4.8.1-1.fc33.x86_64

**Comment by leigh123linux** [comment] 2021-01-15 10:02
> cjs-4.8.1-1.fc33.x86_64

https://bodhi.fedoraproject.org/updates/FEDORA-2021-ad1d60b444

**Comment by Heidistein** [comment] 2021-01-15 10:38
confirm fixed. Thanks!
