### ISSUE TITLE
multicore-sys-monitor@ccadeptic23: Wrong Network Monitoring

### ISSUE THREAD

**Issue by SerafDosSantos** [linuxmint/cinnamon-spices-applets#1190] opened 2017-08-29 15:19 UTC
@jaszhix 

Since my applet update yesterday I've noticed that there's something wrong with a recent change to the applet. Mainly it is the network monitor that is running really wrong.

* It doesn't update the tooltip information
* The interface ids on the network settings show only numbers
* There's something really wrong with the network graphic curves; not behaving like they used to

I'm not sure, but my little finger points to the changes brought up since pull request #1181.

I can't provide logs.

**Comment by jaszhix** [comment] 2017-08-29 15:41
Can you take some screenshots? I'm not quite understanding, it works fine for me. How about some basic environment info? Distro, Cinnamon version, etc?

**Comment by SerafDosSantos** [comment] 2017-08-29 15:57
![screenshot from 2017-08-29 11-53-44](https://user-images.githubusercontent.com/3285430/29830822-4619d2d8-8cb1-11e7-984e-0631a1fefbff.png)
![screenshot from 2017-08-29 11-53-58](https://user-images.githubusercontent.com/3285430/29830821-46188bc6-8cb1-11e7-870f-f3e9f54a19c9.png)
![screenshot from 2017-08-29 11-56-36](https://user-images.githubusercontent.com/3285430/29830820-4612ecb6-8cb1-11e7-882f-3dee05e4ed64.png)

**Comment by jaszhix** [comment] 2017-08-29 16:09
Thanks, yeah I didn't notice that until a second look. I guess some breakage is bound to happen - I've been rewriting a lot of the code. I'll try to get it sorted out soon.

**Comment by jaszhix** [comment] 2017-08-29 16:29
I'm half way tempted to just set the author to none, I don't really want anyone to not feel welcome to submit a PR. Its a pretty hefty applet, and the code has some issues, and bad workarounds the original author documents.

![screenshot from 2017-08-29 11-21-38](https://user-images.githubusercontent.com/6859057/29832080-a4b17fee-8cac-11e7-92b0-38d9ed403b45.png)

For reference, the tooltip data for networks is accurate for me, but I notice the graphs show a steady line near the top, and they're all white. One thing I tried to address was the author adding keyed strings to arrays, and treating it like an object, so I had to redo the iteration inside the network data provider.

I think if you're going to open an issue on something entirely hardware dependent, you should be a _little_ willing to provide more info. Are you using NetworkManager? Try typing ```systemctl status NetworkManager```.

**Comment by SerafDosSantos** [comment] 2017-08-29 19:52
Yes I'm using NetworkManager. I'm more mentioning the problem than being a help to resolve it. You might have some others that will see some problem and use this issue to report it.

The main help I might offer is for you to regress the changes up to #1181. Sorry to be of no more help. I'm no dev or admin, just a simple user.

**Comment by jaszhix** [comment] 2017-08-30 09:07
Yeah, I don't feel like reverting that because the code was too awful. :) I'll work on it soon though.

**Comment by jaszhix** [comment] 2017-08-30 19:08
Can you see if #1195 works any better for you?

**Comment by SerafDosSantos** [comment] 2017-08-31 00:18
The graphical monitor seems fixed but the tooltip, not. I'm constantly connected to a network camera that is streamed through the eno1 interface and nothing shows on the tooltip monitor.

**Comment by jaszhix** [comment] 2017-08-31 01:09
Do you see any errors in ```~/.xsession-errors```?

**Comment by SerafDosSantos** [comment] 2017-08-31 01:54
None that I see. Removed it and re-added it and no errors.

**Comment by jaszhix** [comment] 2017-09-04 23:58
Well I can't reproduce this and you don't want to give me anymore information, so I'm closing this because I don't have time to work on edge cases.

**Closed by jaszhix** 2017-09-04 23:58 UTC
Labels: BUG

**Comment by SerafDosSantos** [comment] 2017-09-05 01:55
@jaszhix Might leave it closed. It might be Cinnamon the problem. I replaced the applet to some similar one and kept having problems. In a fresh updated install.

It's a really nice applet, it ain't just working for me lately. I've been using it for the last three years.

Cheers, keep up the good work.
