### ISSUE TITLE
[temperature@fevimu] Does not load on cinnamon 3.8.8

### ISSUE THREAD

**Issue by trourance** [linuxmint/cinnamon-spices-applets#1937] opened 2018-08-29 15:07 UTC
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

- latest

- System:    Host: archfg Kernel: 4.18.5-arch1-1-ARCH x86_64 bits: 64 Desktop: Cinnamon 3.8.8  Distro: Arch Linux

- ~/.xsession-errors:
`[temperature@fevimu]: No JS module 'panelMenu' found in search path`
`[temperature@fevimu]: Error importing applet.js from temperature@fevimu`

**Notify author of applet**
@jaszhix 

**Issue**
Does not load on cinnamon 3.8.8

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by jaszhix** [comment] 2018-08-29 15:32
Are you using the latest version of the applet? Try upgrading all your applets in System Settings -> Applets.

**Comment by jaszhix** [comment] 2018-08-30 05:31
Closing as I can't reproduce on 3.8, and that error doesn't make sense.

**Closed by jaszhix** 2018-08-30 05:31 UTC

**Comment by trourance** [comment] 2018-08-31 14:17
You're right, it was not updated. Thanks.
