### ISSUE TITLE
weather@mockturtl Weather Status for Today and Tomorrow showing up as black

### ISSUE THREAD

**Issue by CMaclellan** [linuxmint/cinnamon-spices-applets#2837] opened 2020-01-28 15:24 UTC
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
Version 2.3.7 (2020-01-26 16:11:28)

 * Cinnamon version (cinnamon --version)
Cinnamon 4.4.8

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19.3

 * Graphics hardware *and* driver used
Graphics:  Device-1: Intel vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 
           Device-2: NVIDIA GP107M [GeForce GTX 1050 Ti Mobile] driver: N/A bus ID: 01:00.0 
           Display: server: X.Org 1.19.6 driver: fbdev,nouveau,vesa FAILED: nvidia unloaded: modesetting 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel UHD Graphics 630 (Coffeelake 3x8 GT2) v: 4.5 Mesa 19.2.1 
           direct render: Yes 

 * Snippet or attachment of ~/.cinnamon/glass.log
File does not exist

 * Snippet or attachment of ~/.xsession-errors
...
(cinnamon:7768): St-CRITICAL **: 11:07:01.965: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Cinnamon warning: Log level 8: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Cjs-Message: 11:07:01.982: JS LOG: [LookingGlass/info] weather@mockturtl#76: Weather Information refreshed

(cinnamon:7768): St-WARNING **: 11:07:12.645: Ignoring length property that isn't a number at line 1429, col 13

(cinnamon:7768): St-WARNING **: 11:07:12.680: Ignoring length property that isn't a number at line 1429, col 13

(cinnamon:7768): St-WARNING **: 11:07:19.992: Did not find color property '-gradient-start'

(cinnamon:7768): St-WARNING **: 11:07:19.992: Did not find color property '-gradient-end'

(cinnamon:7768): St-WARNING **: 11:07:19.993: Did not find color property '-gradient-start'

(cinnamon:7768): St-WARNING **: 11:07:19.994: Did not find color property '-gradient-end'

(cinnamon:7768): St-WARNING **: 11:07:19.994: Did not find color property '-gradient-start'

(cinnamon:7768): St-WARNING **: 11:07:19.994: Did not find color property '-gradient-end'

(cinnamon:7768): St-WARNING **: 11:07:20.941: Did not find color property '-gradient-start'

(cinnamon:7768): St-WARNING **: 11:07:20.942: Did not find color property '-gradient-end'

(cinnamon:7768): St-WARNING **: 11:07:20.942: Did not find color property '-gradient-start'

(cinnamon:7768): St-WARNING **: 11:07:20.942: Did not find color property '-gradient-end'

(cinnamon:7768): St-WARNING **: 11:07:20.942: Did not find color property '-gradient-start'

(cinnamon:7768): St-WARNING **: 11:07:20.942: Did not find color property '-gradient-end'
Gtk-Message: 11:08:30.208: GtkDialog mapped without a transient parent. This is discouraged.
 ```

**Notify author of applet**
@mockturtl

**Issue**
The font colour for the Weather Status, ie. Snow -4/-1 C, is black while the rest of the font colours are white or blue. The black font colour is difficult to read on the dark background

**Steps to reproduce**
Unknown.

**Expected behaviour**
Weather Status font colour should match the rest of the font colours, ie. White.

**Other information**

**Comment by Gr3q** [comment] 2020-01-28 17:06
Hello,

Do you have a screenshot of the applet?
Also, that theme are you using?

**Comment by CMaclellan** [comment] 2020-01-28 18:14
![weather](https://user-images.githubusercontent.com/47331713/73292419-6adf9380-41d8-11ea-8dd6-44ebc794e9d1.png)

**Comment by CMaclellan** [comment] 2020-01-28 18:18
Changing the Desktop theme seems from macOS-Dark seems to resolve the issue.

**Comment by Gr3q** [comment] 2020-01-29 10:13
Can you tell me where did you get the theme?

I wont be able to fix it otherwise

Thanks

**Comment by CMaclellan** [comment] 2020-01-29 12:53
I believe this is were it came from
https://github.com/B00merang-Project/macOS-Dark

**Comment by Gr3q** [comment] 2020-01-29 18:40
Thank you

**Comment by Gr3q** [comment] 2020-01-29 19:05
I can't reproduce it. Are you running the latest version of the theme?

**Comment by CMaclellan** [comment] 2020-01-30 01:05
You are correct. I must have been running an older version of that theme that was causing the issue.
thanks

**Comment by Gr3q** [comment] 2020-01-30 09:27
@CMaclellan Could you close the issue when you have some time?

Thanks

**Closed** 2020-01-30 11:54 UTC
