### ISSUE TITLE
weather@mockturtl DMI Denmark tomorrow click show wrong hourly forcast

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#3654] opened 2021-02-28 20:21 UTC
```
 * Applet version/Build date 3.0.4 / 2021-02-28 
 * Cinnamon version 4.8.6
 * Distribution - Mint 20.1 Ulyssa and Manjaro Cinnamon 20.2.1 Nibia
 * Graphics hardware *and* driver used - Intel Haswell-ULT Integrated Graphics Controller (i915)
 ```
**Notify author of applet**
@Gr3q  
Congrats and thanks for the very useful new #3603 Hourly feature. The only issue found this far is this: 

**Issue**
When using provider DMI Denmark and clicking on Tomorrow the Hourly show the same left position as Today instead of jumping ahead to Tomorrow. Looks like it is working fine with other providers.

**Steps to reproduce**
1. Right click on applet, Configure.
2. Choose DMI Denmark and set Hourly Forecast Length (hours) to 48.
3. Click open the applet and click on the link Tomorrow.  

**Expected behaviour**
That the Hourly position for Tomorrow and not Today is shown.

**Other information**
When clicking the Weekday after Tomorrow it seems like Tomorrow is shown. 

There is also some confusion regarding the weather Now and Today, see screenshot. Weather is clear but shown as Foggy on Today but this condition looks like a forecast for early morning Tomorrow according to the web site.

![Screenshot from 2021-02-28 21-06-36](https://user-images.githubusercontent.com/5297223/109432281-baf7dd80-7a0a-11eb-98f8-8994381855ae.png)

![Screenshot from 2021-02-28 18-09-04](https://user-images.githubusercontent.com/5297223/109432288-c3e8af00-7a0a-11eb-85ee-00a03162955d.png)

**Comment by Gr3q** [comment] 2021-03-01 08:42
Yeah, for the main issue in short I made them mistake of manipulating the timestamps for daily weather when calculating where the days are in the scrollview. It's completely unnecessary, and it inadvertently changes the date when the date is set to midnight (adding/subtracting hours).

For the other one, I had to come up with a logic to decide which conditions to show for a day, because I have to get them from the hourly/3hourly forecasts.

This is my current logic:
* Gather all conditions for the day we are calculating (6am-6am) - This is a tricky one, because we have to decide when a perceived day boundary is (could use 12am-12am tbh), I simply thought it makes more sense not to split nights into 2, your day starts in the morning and ends in the morning. Please let me know if you disagree.
* I convert all condition codes from night values to day values (if x > 100: x - 100)
* If I have a condition code higher than 10 (anything with precipitation) show that, else show the most common (sunny, cloudy, etc) The problem is that foggy's code is 45, I added that in as an exception.

**Comment by jorgenqv** [comment] 2021-03-01 18:15
Hope there is a good solution to the daily timestamp issue, seems reasonable with start/end in the morning. Just tell me if there is something I can do help out, thanks :+1:

**Comment by Gr3q** [comment] 2021-03-03 08:17
It will be fixed in the next version

**Closed** 2021-03-03 09:29 UTC

**Comment by jorgenqv** [comment] 2021-03-03 16:25
Confirming, works excellent as usual, thnx :)
