### ISSUE TITLE
Incorrect API Key error message weather@mockturtl

### ISSUE THREAD

**Issue by allanmcpherson** [linuxmint/cinnamon-spices-applets#3662] opened 2021-03-03 17:02 UTC
```
Version 3.0.5 (2021-03-03 03:29:25)
Cinnamon 4.4.8
Linux Mint 19.3

error t=2021-03-03T09:14:58Z [weather@mockturtl#79]: Error calling URL: Forbidden, {"error":"API key not valid, or not yet activated."}

On Line: httpLib.js:89:13
[xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/6077711/xsession-errors.txt)

 ```

**Notify author of applet**
@mockturtl 

**Issue**

With the latest update, I started getting Incorrect API error messages using the WeatherBit API.

**Comment by NikoKrause** [comment] 2021-03-03 17:06
@Gr3q is the correct maintainer now

**Comment by NikoKrause** [comment] 2021-03-03 17:10
@allanmcpherson Isn't this a duplicate of your bug report https://github.com/linuxmint/cinnamon-spices-applets/issues/3659?

**Comment by NikoKrause** [comment] 2021-03-03 17:16
@allanmcpherson cam you also do me a favor and try the version from the spices website https://cinnamon-spices.linuxmint.com/applets/view/17

**Comment by allanmcpherson** [comment] 2021-03-03 17:43
This was a new issue. Installing from the website has fixed the problem.

Thanks,
Allan

**Closed** 2021-03-03 17:49 UTC
