### ISSUE TITLE
Cinnamenu@json : Configure on my machine does nothing.

### ISSUE THREAD

**Issue by frankzen** [linuxmint/cinnamon-spices-applets#1725] opened 2018-03-30 14:52 UTC
Version 3.1.3
Cinnamon Version 3.6.7
Debian Sid
Intel on-board graphics standard X driver
There is no glass.log
Nothing of relevance in .xsession-errors
```



@jaszhix

Configure on right click does nothing on my machine. No errors nothing.

**Comment by jaszhix** [comment] 2018-03-30 18:44
Please provide logs and attach them with pastebin anyway.

**Comment by frankzen** [comment] 2018-03-31 12:30
glass.log             https://pastebin.com/2JD7w297

xsession-errors   https://pastebin.com/iy3nA84n

**Comment by jaszhix** [comment] 2018-03-31 13:32
Do you see errors in xsession-errors when you try to change settings? I guess Debian is still packaging CJS 3.2 (mozjs24), which I have not tested with Cinnamon 3.6 - CJS 3.2 uses a very old version of Spidermonkey from 2013. I have tested with Cinnamon 3.2, and it was working a few months ago.

**Comment by jaszhix** [comment] 2018-04-29 05:47
Closing since there has been no follow up, and not reproducible.

**Closed by jaszhix** 2018-04-29 05:47 UTC
Labels: needs more info
