### ISSUE TITLE
betterlock: Notification affected by mouse & typing pointers ! Please, kindly, fix this !!

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-applets#33] opened 2017-01-26 21:57 UTC
Hi. an annoying bug is that: when I activate CapsLock or NumLock during writing (for ex writing in LibreOffice) & applet's notification appear when typing pointer covered by this notification, then I can not continue typing till this notification disappear !!

Also, if applet notification appearing & I bring my mouse' pointer over (under) it then notification will effected (remain sticky & not go to disappear till I remove my mouse' pointer from it's area !!).

Please, kindly, fix this. You already created such fix in Cinnamon own CapsLuck / NumLock notifications option. When I activate Cinnamon own CapsLuck / NumLock notification option from Cinnamon setting, Cinnamon notifications (which appearing in middle lower zone of screen) will never affected by mouse or typing pointers even if pointers within area of Cinnamon notification.

Best.

**Comment by Nokia808** [comment] 2017-01-26 22:11
Applet name is:

Num Lock/Caps Lock indicator with MessageTray notifications by betterlock

UUID as shown in web site is: betterlock

**Comment by Nokia808** [comment] 2017-01-26 22:16
Is this O.K ?? Please it is 1st time to post in GitHub. Just issue me: is it clear or need further information ?

**Comment by jaszhix** [comment] 2017-01-26 22:21
@Cobinja

**Comment by Nokia808** [comment] 2017-02-04 17:27
Is there a plan to address this issue in future?

**Comment by NikoKrause** [comment] 2017-02-13 22:31
I couldn't reproduce your issue. But would it fix your issue, if you had the chance to Hide Notifications?

**Comment by Nokia808** [comment] 2017-02-13 23:08
1) how you could not reproduce this issue ??!!! Just open office document & try to write something while notification covering the pointer of typing then you will encounter it ! If you did or do this & really not encounter this bug, then all what I could say is that I'm on Fedora 24 x64 bit Cinnamon version. I think that you tried on Linux Mint, wasn't it? Please try it on Fedora ......

2) Yes, it will be fixed (or in fact it will be just workaround not real fix) if you add ability to disable notification. Adding this will be good workaround till you find real fix for this issue. 

  Please make new option under name of "Disable notification" not "Hide", because in original GNOME version there is "Hide" option which mean different thing: it mean when CapsLock/NumLuck is inactive by use then corresponding icon in panel will disappear completely & if key is activated then corresponding icon will appear brisky in penal. This nice feature & I recommend you to add it to this important applet.

**Comment by NikoKrause** [comment] 2017-02-13 23:17
I can't reproduce because I can't get the "notification covering the pointer of typing". It's too high:
![screenshot-area-2017-02-14-001447](https://cloud.githubusercontent.com/assets/8415124/22907707/cf59251e-f24a-11e6-9be1-3e14cb636ea6.png)

> you tried on Linux Mint, wasn't it? Please try it on Fedora ......

I'm not going to install Fedora just for this little issue.

**Comment by JosephMcc** [comment] 2017-02-13 23:18
You could try reproducing running the editor in fullscreen.

**Comment by JosephMcc** [comment] 2017-02-13 23:24
The builtin OSD in Cinnamon and the notifications handle mouse clicks differently on purpose. Notifications allow fade on hover or clicking items inside the notification.

**Comment by NikoKrause** [comment] 2017-02-13 23:25
I don't get notifications in fullscreen mode.

**Comment by JosephMcc** [comment] 2017-02-13 23:28
Oh damn. I forgot we block them in fullscreen. You could also alt+click anywhere in the window which will allow you push the titlebar offscreen and position the text area under the notification.

**Comment by NikoKrause** [comment] 2017-02-13 23:33
No problem. I don't see what I write, but after the Notifications faded away, everything what I have written is there.

Tried with xed in Linux Mint 18.1.

**Comment by Nokia808** [comment] 2017-02-14 05:03
Sorry for delay because I was sleeping. 
Good morning all.
Regarding "you could not reproduce it because it is high ........ " though you solve this by full screen, but you can do this by making panel position at bottom instead of being on top.

Regarding you did not reproduce it on Mint 18.1, as I suggest on you: try it on Fedora Cinnamon. No need to install Fedora at all ! Just try it on USB live OS.

Again, I suggest on you to add "Disable Notification" option. By this you will solve this issue by good workaround.

Best & thank you much for your hard effort.

**Comment by NikoKrause** [comment] 2017-02-14 10:13
My panel is at the bottom. And I don't want to download Fedora to be able to reproduce an issue.
If it's an Fedora issue I wouldn't be able to solve it anyway.

What's more interesting:
You could explain what and how you get your cursor so high, when the popup notificafion is at the very edge of the screen. Maybe with some Screenshots.

**Comment by NikoKrause** [comment] 2017-02-14 10:15
Also there is a pull request waiting, which adds the ability to turn off the notifications. Since it's a new feature it needs the approval of the author.

I'm not sure what were doing, when he doesn't show up. He seems to have abandoned this applet years ago.

**Comment by Nokia808** [comment] 2017-02-14 12:27
Hi.  Dear Niko, this bug is more annoying when panel set at bottom on screen & user typing in office document & reach to lower part of page & being within area of notification then need to change CapsLock /NumLock key. At this situation (being at lower part of screen within office document + within area of notification) then activating/deactivating key will break typing process ...... . Not all users prefer panel at top of screen. Personally I changing the position of panel about month at top & month at bottom.

Regarding the author of this applet, let we suppose that for a cause or other will never replay you to give his permission (being die, handicap by rood traffic accident, ........... ) what is the fate of his project ? This is not specific for this applet but general for all open source project.

Being an open source object mean - as I understood, correct to me if I'm wrong - any one is free to make use & MAKE CHANGE of project with difference to original author, isn't it? Does the scientist who found General Licence Foundation take permission from Unix founder company to develop GNU OS ? Certainly no. He depend on original open source (free) version of Unix to develop GNU OS, wasn't it? I think it is same with our case regarding this issue: give a time for author to wait his response & permission. If not replay then behave. What is the problem?

**Comment by NikoKrause** [comment] 2017-02-14 12:40
If he doesn't appear, it had to be forked by someone, who is willing to maintain it.
You can't publish it under his name.

**Comment by Nokia808** [comment] 2017-02-14 12:46
By the way, I noticed that notification did not appear when I used full screen mode ! I remember that notification was appearing if I used full screen mode! Do you modify applet for this or this new bug?!

**Comment by collinss** [comment] 2017-02-15 00:13
@Nokia808 
I just took a quick peek at the code, and it looks like this applet uses the built-in code for sending notifications. This means that it is almost certainly not a problem with the applet but with Cinnamon itself. See if you can reproduce it with a test notification (go to cinnamon-settings -> notifications -> Display a test notification).

**Comment by Nokia808** [comment] 2017-02-15 09:20
@colliness
Yes, you are correct ! 
But why Cinnamon's build-in CapLock/NumLock notification not affected by mouse or typing pointer at all being completely not interfere with them as if it not existing ?

**Comment by JosephMcc** [comment] 2017-02-15 09:24
@Nokia808 I answered that above. A notification and the OSD that cinnamon is using for caps lock aren't the same thing. One requires interaction with the mouse so captures it, the other doesn't.

**Comment by collinss** [comment] 2017-02-15 13:54
Since this issue is not specific to or caused by this applet, I'm closing this. Feel free to open an issue with Cinnamon instead, or else report it to Fedora since it doesn't seem to effect Mint.

**Closed by collinss** 2017-02-15 13:54 UTC
Labels: BUG
