### ISSUE TITLE
Applet Bug : After resume from suspend, display of the forecast is shrinked (~no padding between icons)

### ISSUE THREAD

**Issue by Sabilon** [linuxmint/cinnamon-spices-applets#6390] opened 2024-09-09 06:06 UTC
### Applet version/Build date

3.6.4

### Cinnamon version

6.2.9

### Distribution

Mint 22

### Graphics hardware *and* driver used

Nvidia 1660 super / 550

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

![Weather applet after resume from suspend](https://github.com/user-attachments/assets/c69a42c7-c329-4dac-8fd7-11cfd89200ce)
This bug occurs on all computers I use, since several years I would say. Restarting Cinnamon from the contextual menu is a workaround. 
[cinnamon.log](https://github.com/user-attachments/files/16926102/cinnamon.log)

**Comment by Sabilon** [comment] 2024-09-09 06:12
Probably a duplicate of #5581

**Comment by Gr3q** [comment] 2024-09-09 07:27
It is a duplicate, I still don't know what causes it. It happens when the data is refreshed while the menu is open.

**Comment by rcalixte** [comment] 2024-09-10 02:45
Duplicate of #5581

**Closed by rcalixte** 2024-09-10 02:45 UTC
Labels: BUG
