### ISSUE TITLE
weather@mockturtl help tab has no scroll bar - Feature request?

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-applets#3383] opened 2020-12-22 23:26 UTC
```
 * Applet version/Build date Version 2.6.9 (2020-11-26 15:00:10)
 * Cinnamon version Cinnamon 4.6.7
 * Distribution - Mint 20 Cinnamon 64 bit
 * Graphics hardware Intel Core i7-8550U


**Notify author of applet**
@mockturtl

**Issue**
1920x1080 screen and unless I full the window it's tough to see the help tab in configure window.
Right click on applet in panel, pick configure and then click help in menubar
There should be a scroll bar.  
I did find that the default width makes the height extreme and either widen the window or hitting maximize corrects the issue.   
But I think it would be better to have a scroll bar if the window was defaulting to this size.
![Weather-default](https://user-images.githubusercontent.com/26556059/102942335-1645a680-4483-11eb-9c28-d16dcd0f5c0e.png)

This is stretched top the bottom.  
![Weather-issue](https://user-images.githubusercontent.com/26556059/102942354-265d8600-4483-11eb-878d-30f71ec1945d.png)

But as said, maximize solves the issue, but it's not intuitive.

**Comment by Gr3q** [comment] 2020-12-26 21:21
This is an issue with Cinnamon https://github.com/linuxmint/cinnamon/issues/9512, I can't do much with it if they don't fix this.

**Comment by Gr3q** [comment] 2020-12-26 21:22
Also, this issue is a duplicate of https://github.com/linuxmint/cinnamon-spices-applets/issues/3169

**Comment by ChooChooAl** [comment] 2020-12-26 22:09
As long as someone knows. That's the end of my duties.
Thanks.

**Closed** 2021-01-10 16:05 UTC
