### ISSUE TITLE
ScreenShot applet does not scale properly

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-spices-applets#1723] opened 2018-03-29 08:40 UTC
What the title of this report, or some sort of title with the applet? Anyhow, that 'UUID' is: ScreenShot@tech71

```
 * Applet version/Build date (to be found in "About.." or in "metadata.json") 2017-10-22
 * Cinnamon version (cinnamon --version) 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: Intel Kabylake GT1.5; 3.0 Mesa
 * Snippet or attachment of ~/.cinnamon/glass.log: I found nothing that looked relevant.
 * Snippet or attachment of ~/.xsession-errors
29/03/2018 09:37			2018-03-29 09:28:44,995 | [1;33mWARNING[0m | ulauncher.util.image_loader: load_image() | Could not load image /usr/share/pixmaps/nemo.xpm. E: g-file-error-quark: Failed to open file '/usr/share/pixmaps/nemo.xpm': No such file or directory (4)
29/03/2018 09:37			SIOCGIFADDR: Cannot assign requested address
29/03/2018 09:37			mintUpdate: no process found
29/03/2018 09:37			Cinnamon warning: Log level 16: STACK_OP_LOWER_BELOW: sibling window 0x720000b not in stack
29/03/2018 09:37			Icon theme "oxygen" not found.
29/03/2018 09:37			Icon theme "oxygen" not found.
29/03/2018 09:37			Error: standard icon theme "oxygen" not found!
29/03/2018 09:37			ksystemlog:  Log manager is not yet initialized
29/03/2018 09:37			doesn't know "/var/log/syslog"
29/03/2018 09:37			Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x7401ca1 (Open Locat)
29/03/2018 09:37			Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x7402731 (Open Locat)
29/03/2018 09:37			doesn't know "/home/nicholas/.xsession-errors"
29/03/2018 09:38			Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x74046a0 (Save selec)

 ```

 That list says no author is assigned. (Reporting this bug could be easier, I am finding!)

**Notify author of applet**

**Issue**

This applet does not always scale properly. Screenshot (the tiny square - third icon from the right - is the camera icon for the screenshot applet - miniturarised!):

![image](https://user-images.githubusercontent.com/9998846/38078263-9ee9348e-3333-11e8-82c4-61b319a5408a.png)

Steps to reproduce

The problem may be reproducable on Mint out of the box. If not, try enlarging the panel. If that still doesn't do it, go hiDPI. Themes do not seem to affect the problem, except in that changing theme temporarily (_temporarily_) fixes the problem.

Expected behaviour

The icon should scale properly, always.

Other information

The icon does occasionally - either immediately after adding to the panel, or, as mentioned above, after changing Cinnamon theme - scale correctly.

**Comment by smurphos** [comment] 2018-03-29 09:20
What icon theme are you using? The tiny icon I can see doesn't look like the stock icon you would get if using any of the stock icon themes,

A work-around is to add the screen-shot app to the panel as a panel launcher. It has got right click shortcut actions.

**Comment by NikoKrause** [comment] 2018-03-29 09:34
Looks a lot like #1222, which was fixed by https://github.com/linuxmint/cinnamon-spices-applets/pull/1226

**Comment by CottonEaster** [comment] 2018-03-29 09:39
@smurphos 
That tiny icon is, I believe, a verrry small version of a camera icon. At any rate, on those occasions that the icon appears normal-sized, the icon is of a camera. As to your workaround: thanks, I'll try it. What's the name of the app you have in mind (the one I'm to add as a launcher)?

**Comment by smurphos** [comment] 2018-03-29 09:56
The app is gnome-screenshot, appears as Screenshot in the menu. It is the same app as the applet uses. 

Re the icon theme - I can make out it's a camera - but it doesn't look like the same camera icon as the Mint-X or Mint-Y theme would give. Plus I note your xsessions-error.log is complaining about missing the oxygen icon theme. So I'm wondering if there is an icon-theme issue and the icon theme you are using inherits from oxygen. 

I can't reproduce the issue with Mint X, Mint Y or the 3rd party Vibrancy colours icon themes.

**Comment by CottonEaster** [comment] 2018-03-29 10:18
It hadn't occured to me that it might be an *icon* theme issue - though I suppose it should have done. I am using [the paper theme](https://github.com/snwh/paper-icon-theme) - which has no open bug report relating to the camera icon. Nor did a code search for 'oxygen' find a match in that theme's code on github.

I changed my theme to Mint-Y and the icon size of the tiny camera icon did not change - not even after restarting Cinnamon (via the 'troubleshooting' menu).

**Comment by smurphos** [comment] 2018-03-29 10:47
Paper has an appropriate icon which is the one in the screenshot - https://github.com/snwh/paper-icon-theme/blob/master/Paper/scalable/devices/camera-photo-symbolic.svg - I guess  NikoKrause has hit the nail on the head then. NikoKrause knows more than me anyway.... ;-). Odd how it doesn't affect everyone the same.

**Comment by CottonEaster** [comment] 2018-03-29 10:53
So, a bug with the Paper theme or with the applet (or with Cinnamon), I wonder! Thanks to you both for your help.

**Comment by NikoKrause** [comment] 2018-03-29 12:03
It's definitely not an issue with the theme. I can reproduce this with Mint-Y.
I'll posted the solution to this problem.
@CottonEaster Can you fix this and create a Pull Request.

**Comment by smurphos** [comment] 2018-03-30 03:28
[ScreenShot@tech71.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/1862580/ScreenShot.tech71.zip)
 @CottonEaster - can you test the attached to see if it fixes the issue? Extract to ~/.local/share/cinnamon/applets

It also allows for more than once instance of the applet (i.e you could have one on each panel if you have multiple panels).

**Comment by CottonEaster** [comment] 2018-03-31 22:19
I'm trying the revised version of the applet and it seems to be working well with no size problems. Good stuff.

**Comment by smurphos** [comment] 2018-04-01 09:30
Thanks for testing - I probably haven't got time today but will get the PR submitted shortly.

**Closed** 2018-04-02 11:23 UTC
Labels: In Progress
