### ISSUE TITLE
feeds@jonbrettdev.wordpress.com: cannot update

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-spices-applets#58] opened 2017-02-01 19:41 UTC
Since the latest change on github the feeds-applet cannot be updated. Error in Cinnamon:
...
Details: [Errno 2] file or folder not found: '/tmp/tmpmHmke1/metadata.json'

**Comment by Odyseus** [comment] 2017-02-01 19:50
I can confirm this error too. The applet cannot be updated (nor installed if it doesn't exists).

The same error than the one reported by @Mintulix is presented (different path, of course).

**Comment by NikoKrause** [comment] 2017-02-01 20:44
I can confirm this problem as well. Maybe it has something to do with the cache of the spices website, because the files (metadata.json) were moved from "files" to "files/feeds@jonbrettdev.wordpress.com" in one of the last commits.

**Comment by Mintulix** [comment] 2017-02-02 19:01
Hey, it's fixed already. Thanks.

**Comment by Mintulix** [comment] 2017-02-03 17:44
I was wrong or it is broken again. Same error, different tmp-path.

**Comment by Odyseus** [comment] 2017-02-03 19:04
Hello, everybody.

I installed absolutely all available applets on my system just to check if other applets have the same error. The following applets can't be installed/updated from Cinnamon's applets manager.

- feeds@jonbrettdev.wordpress.com
- gputemperature@silentage.com
- windowButtons@lippy
- classicMenu@dalcde

They all have one thing in common, their *files* folder contain several files along the applet folder. So, maybe moving those files outside that folder would solve the problem?

@NikoKrause or @collinss ^^^

**Comment by NikoKrause** [comment] 2017-02-03 20:16
I can try it with the feeds applet.

**Comment by NikoKrause** [comment] 2017-02-03 20:34
I die know about the other 3 applets. I did exactly the same a few days ago, installed all applets.

ClassicMenu seems broken to me beyond repair. At least I never saw it working ;)

I moved the gitignore in feeds folder. It's already on spices Website. It needs longer to appear on System Settings. Don't know how long it takes thought.

**Comment by Mintulix** [comment] 2017-02-03 20:44
Updated feeds applet sucessfully again. I won't close it for now, just wait a few days and watch if it happens again for any reason.

**Comment by NikoKrause** [comment] 2017-02-03 20:48
I had the same feeling as Odyseus a few days ago. But it seems I didn't waited long enough.

We need to test it with another applet later.

**Comment by Odyseus** [comment] 2017-02-03 22:21
@NikoKrause.

It seems to work normally now. I can install and update the feeds@jonbrettdev.wordpress.com applet from System Settings.

It's worth noticing the following:
- In my Cinnamon 3.0.7 LM 18 system I had the feeds@jonbrettdev.wordpress.com applet installed manually. It was still impossible to update it from the applets manager. I had to remove the applet and delete its settings folder and then I was able to install it from the applets manager.
- In my Cinnamon 3.2.8 LM 18.1 system I hadn't this applet installed. After refreshing the applets cache, the applet installed at once without any errors. I removed it and re-installed it several times to test, and still no errors.

@jake1164

There is a typo inside the metadata.json file. It reads **max-instanceso** instead of **max-instances** (note the letter "o" in the former). This forces the applet to only allow one instance of it to be placed in a panel.

**Comment by NikoKrause** [comment] 2017-02-04 10:56
I tested the gputemperature@silentage.com now. Need to wait a little bit to get everything updated.

> Since the .gitignore file has been moved one level up, its content should be edited to point to the correct path (if needed).

I have edited the gitignore file before I moved it.

**Comment by jake1164** [comment] 2017-02-04 12:55
@Odyseus 

Thanks for pointing it out, I will update that in next revision.

**Comment by NikoKrause** [comment] 2017-02-04 16:42
The gputemperature seems to be installable now. Can anyone confirm as well?

**Comment by Mintulix** [comment] 2017-02-04 17:05
Hi Niko, I can confirm this, although I didn' test it before the fix.

**Comment by Odyseus** [comment] 2017-02-04 17:06
@NikoKrause: Confirmed, the gputemperature@silentage.com applet installed at once without any errors. 👍

**Comment by jake1164** [comment] 2017-02-05 01:23
OK, I am at a loss.. I have tested the following: 

- upgrading on Fedora 25 - Cinnamon 3.2.8  
- Removing applet (uninstalling), removing the feeds directory in .cinnamon folder (uninstall should do this but another problem for another day)
- Upgrading on Mint 18 - Cinnamon 3.0.7
- Removing and installing fresh 
- Fresh install on Mint 18.1 - Cinnamon 3.2.7

**Comment by NikoKrause** [comment] 2017-02-05 01:40
And what's the problem?

**Comment by jake1164** [comment] 2017-02-05 13:20
I cant reproduce this issue, or is the issue just updating the json file now?

**Comment by schi2m** [comment] 2017-02-06 15:26
[Errno 2] Nie ma takiego pliku ani katalogu: '/tmp/tmpfo92MK/metadata.json'

I try to install classic menu from cinnamon add applet window.

**Comment by NikoKrause** [comment] 2017-02-06 16:35
@schi2m 
The classic menu is broken.

**Comment by Odyseus** [comment] 2017-02-06 18:24
Hello, everybody.

@NikoKrause: I think it's time to close this issue since the main issue reported by @Mintulix is already fixed.

And you should move the files of the other applets that present the same error (windowButtons@lippy and classicMenu@dalcde). It doesn't matter if the applet doesn't really work, that can be dealt with later. What matters is that people doesn't keep reporting an error that you already know how to fix.

**Closed** 2017-02-06 18:28 UTC

**Comment by NikoKrause** [comment] 2017-02-07 01:57
I moved the files from those two applets.
And I fixed the windowButton applet. I hope it'll work.
