### ISSUE TITLE
weather@mockturtl: "Cloudiness" missing colon and German translation

### ISSUE THREAD

**Issue by Kabuse** [linuxmint/cinnamon-spices-applets#2808] opened 2020-01-11 10:26 UTC
Linux Mint 19.3 Tricia x86_64
Cinnamon 4.4.8
Weather (weather@mockturtl) Version 2.3.5 (2020-01-09 21:29:23)

If you open the applet, it shows you the current values in the upper right corner.

There is also the value "Cloudiness".

First issue, I want to mention is, that all other descriptors, like "Temperature" or "Humidity" are followed by a colon, but not "Cloudiness". I think this should be done, so it is more consistant.

Second issue, I am in Germany here, the translation of "Cloudiness" is missing. I would like to propose "Bewölkung" as the corresponding term in German language.

Thanks.

**Comment by Gr3q** [comment] 2020-01-12 17:58
Hello,

 I will look into it. In the meantime can you do a screenshot about the problem? as a reference for me.

Thanks

**Comment by Kabuse** [comment] 2020-01-12 19:26
Thank you for the reply, sure, no problem!

![weather_applet_screenshot](https://user-images.githubusercontent.com/13647006/72224349-db9c7400-3579-11ea-8f2a-a4c2ff3d3f38.png)

**Comment by Kabuse** [comment] 2020-01-12 19:46
Btw, what I just noticed. For the wind speed, the German translation for kph (km/h) is also not working. In the settings, I can choose "km/h", but in the applet, it still says "kph" :-)

![Bildschirmfoto vom 2020-01-12 20-40-20](https://user-images.githubusercontent.com/13647006/72224607-831aa600-357c-11ea-81c5-9e0969c19669.png)

**Comment by Odyseus** [comment] 2020-01-13 02:41
Hello, everybody.

@Gr3q: The problem is that the German localization needs to be updated. It contains the translation for the string `Cloudiness:` but not for the string `Cloudiness` (without colon). The retrieved string in [this call](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/weather%40mockturtl/files/weather%40mockturtl/3.8/applet.js#L537) is `Cloudiness`, which will not be translated to German.

As for the wind speed unit not being translated, the German translation does contain the localization, [but it isn't used by calling `_()`](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/weather%40mockturtl/files/weather%40mockturtl/3.8/applet.js#L533).

**Comment by Gr3q** [comment] 2020-01-13 18:40
The problem was [here](https://github.com/linuxmint/cinnamon-spices-applets/blob/f95af4e9c0d206370563c7ad30e4f69e0b7ebeac/weather%40mockturtl/src/openWeatherMap.ts#L123), I guess I forgot to add the colon one step before, same with Feels Like with DarkSky.

It will be fixed in the next update soon

**Closed** 2020-01-20 23:16 UTC
