### ISSUE TITLE
weather@mockturl - Missing hourly forecast

### ISSUE THREAD

**Issue by nerozero** [linuxmint/cinnamon-spices-applets#6034] opened 2024-05-26 14:14 UTC
### Applet version/Build date

3.5.0

### Cinnamon version

6.0.4

### Distribution

mint 21.3

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

After yesterday update hourly forecast dissapeared for OpenWeatherMap data service. 
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/18283531/a39b013f-38b2-4836-a545-ee4ab724d9bf)

**Comment by haggen88** [comment] 2024-05-26 14:34
I confirm the bug

**Comment by Gr3q** [comment] 2024-05-26 20:27
Please refer to https://github.com/linuxmint/cinnamon-spices-applets/issues/6033

**Comment by rcalixte** [comment] 2024-05-27 03:07
Duplicate of #6033

**Closed by rcalixte** 2024-05-27 03:07 UTC
Labels: BUG
