### ISSUE TITLE
better-backgrounds@simonmicro: Bug

### ISSUE THREAD

**Issue by binyominzeev** [linuxmint/cinnamon-spices-applets#6227] opened 2024-07-21 10:41 UTC
### Applet version/Build date

Updated on 2024-07-21 05:34:33

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Applet name and maintainer

better-backgrounds@simonmicro @simonmicro

### What happened?

No background updates since last applet update. Also, current background disappeared after first restart.

**Comment by binyominzeev** [comment] 2024-07-21 14:17
(Two times I started it did not work, now it started worked again.)

**Comment by simonmicro** [comment] 2024-09-01 10:36
Duplicate of https://github.com/linuxmint/cinnamon-spices-applets/issues/6193 / https://github.com/simonmicro/better-backgrounds/issues/26 ?

**Comment by rcalixte** [comment] 2024-09-02 03:47
Duplicate of #6193

**Closed by rcalixte** 2024-09-02 03:47 UTC
Labels: BUG
