### ISSUE TITLE
Cinnamenu@json keyboard navigation problem

### ISSUE THREAD

**Issue by melomane63** [linuxmint/cinnamon-spices-applets#4438] opened 2022-08-22 23:51 UTC
* Version 5.0.1 (2022-08-20 07:14:57)
 * Cinnamon 5.4.10
 * Mint 21
 ```

Notify author of applet
@fredcw

Issue
in grid view , is not possible to retourn to category view from app view

**Steps to reproduce**
open menu, use the arrows to choose a category, then use the right arrow to go to the applications view. now it is impossible to retour with keyboard to category view

**Expected behaviour**

retour to category view from app view with keyboard

**Other information**

Work as expect in list mode.

**Comment by fredcw** [comment] 2022-08-23 01:31
@melomane63 This is actually by design, with the idea that people would use the Tab key to switch between apps, categories, and sidebar. However, as I've now discovered thanks to your bug report, the tab key no longer works in Cinnamon 5.4.x. I will have a fix for this in the next update.

**Closed** 2022-08-30 18:54 UTC
