### ISSUE TITLE
Spices website: old versions of applets being downloaded

### ISSUE THREAD

**Issue by cardsurf** [linuxmint/cinnamon-spices-applets#2451] opened 2019-06-15 06:27 UTC
Technical information:
Linux Mint 19.1
Firefox 67.0

Issue description:
When pressing `Download` button on Spices website old versions of applets are downloaded.

Steps to reproduce:
1. Download an applet from the Spices website in Firefox by pressing `Download` button.
2. Update applet code like [here](https://github.com/linuxmint/cinnamon-spices-applets/pull/2425).
3. Same as step 1.

Expected result:
Updated applet version is downloaded.

Actual result:
Old applet version is downloaded.

Details:
When a user visit Spices website for the first time the .zip archive with applet files is downloaded correctly:

![1](https://user-images.githubusercontent.com/3139729/59547904-f2bcaa00-8f35-11e9-8c9b-3d36adee38bc.png)

A response contains key value-pair `cache-control: max-age=31536000` in a header. The value is equal to 31536000 / 3600 / 24 = 365 days. 
Once the .zip file is downloaded and `Download` button is pressed then files are fetched from browser cache instead of being downloaded from a server:

![2](https://user-images.githubusercontent.com/3139729/59547912-ff410280-8f35-11e9-9681-d19b98f0eba7.png)

The caching algorithm in Firefox works as described [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching):
The freshness lifetime is calculated based on several headers. If a `Cache-control: max-age=N` header is specified, then the freshness lifetime is equal to N. If this header is not present, which is very often the case, it is checked if an `Expires` header is present. If an `Expires` header exists, then its value minus the value of the `Date` header determines the freshness lifetime. Finally, if neither header is present, look for a `Last-Modified` header. If this header is present, then the cache's freshness lifetime is equal to the value of the `Date` header minus the value of the `Last-modified` header divided by 10.

One way to correct the issue is to disable browser cache. This make the browser send `Cache-control: no-cache` header to the server and download the .zip archive from the server:

![3](https://user-images.githubusercontent.com/3139729/59547913-049e4d00-8f36-11e9-99d8-0fd46264972c.png)

To reproduce the issue: 
Download one of the applets in Firefox for which there is currently a pull request. Then download it again when a pull request is merged into master.

**Comment by claudiux** [comment] 2019-06-17 15:10
The json file https://cinnamon-spices.linuxmint.com/json/applets.json is not up to date. The Spices Update applet has 22 stars since last Friday (https://cinnamon-spices.linuxmint.com/applets/view/309), and only 20 are indicated in this json file.
![Capture du 2019-06-17 17-00-37](https://user-images.githubusercontent.com/33965039/59614718-928a5b80-9121-11e9-8171-9acbdb90a460.png)
Maybe a faulty service?

**Comment by cardsurf** [comment] 2019-06-17 16:07
> The json file https://cinnamon-spices.linuxmint.com/json/applets.json is not up to date. The Spices Update applet has 22 stars since last Friday (https://cinnamon-spices.linuxmint.com/applets/view/309), and only 20 are indicated in this json file.
> ![Capture du 2019-06-17 17-00-37](https://user-images.githubusercontent.com/33965039/59614718-928a5b80-9121-11e9-8171-9acbdb90a460.png)
> Maybe a faulty service?

@claudiux 
When I download applets.json file it also shows `score: 20` for SpicesUpdate applet. So you are not alone with the issue.

**Comment by claudiux** [comment] 2019-06-18 00:30
I think our problems have the same cause.

**Comment by smurphos** [comment] 2019-06-18 05:41
This issue affects downloads / updates via the Cinnamon settings modules
as-well, and has been prevalent for at least a few months.  It takes a few
days for updated spices to be correctly downloaded.

**Comment by claudiux** [comment] 2019-06-25 08:59
@clefebvre : The json files containing the information about the xlets are not up to date. The service seems to have been down for at least 17 days.

**Comment by claudiux** [comment] 2019-07-21 21:43
@cardsurf: This issue seems solved: https://github.com/linuxmint/cinnamon/issues/8712.

**Comment by cardsurf** [comment] 2019-07-23 16:09
@claudiux Unfortunately I think that the issue is still present.
Yesterday I downloaded Spices Update applet using the steps I described when the [pull request](https://github.com/linuxmint/cinnamon-spices-applets/pull/2482) was opened.
Today the pull request is merged into master. Then I download the applet again with `Download` button I get cached version. `metadata.json` file still has `"version": "2.0.0"` in it.
The same happens when I installed the applet today through `Applets` system app.
Can you reproduce the above steps with the website for an opened pull request ?

**Comment by claudiux** [comment] 2019-07-23 23:16
@cardsurf Ok, I see. If you use the Download button, which link to https://cinnamon-spices.linuxmint.com/files/applets/SpicesUpdate@claudiux.zip, then a cached version of this zip file is downloaded.

But, if you add a question mark at the end of this URL, that forces the server to send the latest version: https://cinnamon-spices.linuxmint.com/files/applets/SpicesUpdate@claudiux.zip?

@clefebvre Is it possible to add this question mark at the end of the Download button link?

**Comment by claudiux** [comment] 2019-08-04 17:07
For cinnamon-settings, https://github.com/linuxmint/cinnamon/pull/8746 solves this issue.

For the Download button of the Spices web site, the problem is still present:
![Capture du 2019-08-04 18-58-59](https://user-images.githubusercontent.com/33965039/62426849-8adf4000-b6ea-11e9-886f-233763dbe15c.png)
You can see that this applet was updated 22 hours ago and that the downloaded zip file is 6 months old.

**Comment by claudiux** [comment] 2020-09-24 19:51
This issue is still present.

**Comment by NikoKrause** [comment] 2020-11-05 20:35
This should be fixed now

**Closed by NikoKrause** 2020-11-05 20:35 UTC
