### ISSUE TITLE
[sticky@scollins] copy/paste doesn't work

### ISSUE THREAD

**Issue by Sadi58** [linuxmint/cinnamon-spices-applets#2217] opened 2019-01-18 08:35 UTC
Using the latest applet version under LinuxMint 19.1, Cinnamon 4.0.9,
I can't use Copy, Cut, Paste commands (via shortcut keys or right-click)

**Comment by icarter09** [comment] 2019-01-21 14:21
@Sadi58 is this issue in response to a specific applet?

**Comment by Sadi58** [comment] 2019-01-21 15:57
@icarter09 Sorry, I forgot to specify the applet, I'lltry and fix the title.

**Comment by collinss** [comment] 2019-01-21 22:38
Hi @Sadi58. Could you give more details? It works fine for me (same versions), so it's pretty much impossible to figure out why it's breaking for you without some more information. Could you, for example, tail -f .xsession-errors in a terminal and see if anything pops up when you try to copy/paste? Also, is it broken when copying to/pasting from certain apps and not others, or does it seem to be a problem for all of them?

**Comment by Sadi58** [comment] 2019-01-22 08:54
Hi @collinss , this looks like an erratic and inconsistent behavior, I'll try to give some details:
1) I've never seen the context menu item "Paste" working.
2) Keyboard shortcut Ctrl+V works only after manually entering something, but not on a blank line. Terminal output for this is below. I hope this helps at least as a start, otherwise I'll try to give more details.

```
(cinnamon:3384): Cjs-CRITICAL **: 11:47:02.444: Object St.IMText (0x5572c7182fc0), has been already finalized. Impossible to get any property from it.
== Stack trace for context 0x5572c1ad64c0 ==
#0 0x5572c21c96e0 i   /usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function:1087 (0x7f4e0f343bc0 @ 88)
#1 0x5572c21c9620 i   self-hosted:916 (0x7f4e378e4560 @ 367)

(cinnamon:3384): Cjs-CRITICAL **: 11:47:02.445: Object St.IMText (0x5572c7182fc0), has been already finalized. Impossible to set any property to it.
== Stack trace for context 0x5572c1ad64c0 ==
#0 0x5572c21c96e0 i   /usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function:1088 (0x7f4e0f343bc0 @ 101)
#1 0x5572c21c9620 i   self-hosted:916 (0x7f4e378e4560 @ 367)
Cinnamon warning: Log level 8: gtk_im_context_focus_out: assertion 'GTK_IS_IM_CONTEXT (context)' failed
```

**Comment by collinss** [comment] 2019-01-23 01:33
@Sadi58 Do you by any chance have any accessibility features enabled (such as a screen reader)? It looks like that error is related to that.

**Comment by Sadi58** [comment] 2019-01-23 06:45
@collinss you're right, apparently on-screen keyboard was enabled, and disabling it fixed the issue with pasting via keyboard shortcut.
However, although not so crucial anymore, context menu item paste still doesn't work FYI.

**Comment by collinss** [comment] 2019-01-23 21:10
That's Ok, I already found a fix for the context menu issue anyway. I didn't push my fix yet because I wanted to figure out what was causing the keyboard shortcut issue so I could do it all at once. It was due to a change that was made to cinnamon's clipboard handling a year or so ago. I never noticed the issue because I usually use the keyboard for such things. Since it's looking more like a problem with Cinnamon, I'm going to just go ahead an push my fix and see if I can figure out the on-screen keyboard interfering with copy/paste issue separately.

**Comment by collinss** [comment] 2019-01-24 02:12
hmm... I still can't seem to reproduce the issue with the on-screen keyboard enabled, so I still don't know what's causing it. Oh well, I guess I'll close this for now since it's working for you again.

**Closed by collinss** 2019-01-24 02:12 UTC

**Comment by Sadi58** [comment] 2019-01-24 09:08
OK.
BTW, when you mentioned accessibility features such as a screen reader, I saw that on-screen keyboard was enabled but actually there was no on-screen keyboard on sight ;-)
Now I enabled it again to check it out, and an on-screen keyboard was displayed without causing a similar problem.
It must have been a weird one-off thing then I assume...
Thanks a lot for fixing this!

**Comment by collinss** [comment] 2019-01-24 22:45
Ah, OK. Good to hear. I'll just assume that there's nothing else needed then.
