### ISSUE TITLE
Cinnamenu@json - bug

### ISSUE THREAD

**Issue by oldtomdevel** [linuxmint/cinnamon-spices-applets#3203] opened 2020-08-25 17:57 UTC
The Applet Cinnamenu@json has a little bug as follows.
The entry "favorite apps" in the category list on the left is not translated into the local language after system start (while all other entries are correctly translated).
But after having opened the applet settings and just having toggled (i.e. turning on and immediatly turning off) e.g. the setting "add favorites to session buttons" (or similar, this is just my own translation back to english), the entry "favorite apps" is correctly translated.
This funny behaviour can be observed in Linux Mint 19.2 Cinnamon and sometimes in Linux Mint 20 Cinnamon. I was not able to find out what triggers the bug i.e. what circumstances make the bug happen.
However, in LMDE 4 Debbie the applet always works fine i.e. I have never observed the bug.
All my observations refer to systems with German language and with "gnome" icon set selected.

**Comment by oldtomdevel** [comment] 2020-08-27 14:58
... additional observation:
the not translated entry "favorite apps" eventually gets translated as expected. However, this takes a long time e.g. some hours. That is, after power-up the entry is not translated, but after some hours of operation (without changing the settings of Cinnamenu) the surprise happens and the entry suddenly becomes translated.

**Comment by fredcw** [comment] 2020-09-23 16:22
@oldtomdevel That sounds like a very strange bug. Unfortunately, I can't reproduce it.

**Comment by oldtomdevel** [comment] 2020-10-05 14:14
Meanwhile, I have upgraded my main machine to LM20 with Cinnamenu 4.5.
Everything works fine there.

But I have an older testing machine still running with LM19 and Cinnamenu 4.4, where the funny bug as described above still exists. One more observation: changing the icon set in Menu->Settings->Theme e.g. from gnome to Mint-X-Aqua or back leads to an immediate change of the entry "favorite apps" into the correctly translated one.

It is a very strange bug indeed.

**Comment by NikoKrause** [comment] 2021-02-23 19:51
Duplicate of https://github.com/linuxmint/cinnamon-spices-applets/issues/3623

**Closed by NikoKrause** 2021-02-23 19:51 UTC
